force-app/main/default/objects/Income_Card_Payment__c/Income_Card_Payment__c.object-meta.xml
<CustomObject>
    <description>Smarter Pay - Card Payment Detail</description>
    <label>Card Payment Detail</label>
    <nameField>
        <displayFormat>HUAPP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Income_Card_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Income_Card_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Order_ID__c.field-meta.xml
<CustomField>
    <fullName>Order_ID__c</fullName>
    <description>Payment Intent   If First Payment is collected
Setup Intent , If No Payment is collected</description>
    <inlineHelpText>Payment Intent /Setup Intent Id</inlineHelpText>
    <label>Setup/Payment Intent Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Total_Amount_Taken__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Taken__c</fullName>
    <label>Total Amount Taken</label>
    <summarizedField>Income_Card_Payment_History__c.Credit_Amount__c</summarizedField>
    <summaryForeignKey>Income_Card_Payment_History__c.Income_Card_Payment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment_History__c/Income_Card_Payment_History__c.object-meta.xml
<CustomObject>
    <label>Card Payment History</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Income Card Payment History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Income_Card_Payment_History__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment_History__c/fields/Income_Card_Payment__c.field-meta.xml
<CustomField>
    <fullName>Income_Card_Payment__c</fullName>
    <label>Income Card Payment</label>
    <referenceTo>Income_Card_Payment__c</referenceTo>
    <relationshipName>Income_Card_Payment_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment_History__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <label>Transaction Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <description>Donation Type</description>
    <label>Donation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donation_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Donor_ID__c.field-meta.xml
<CustomField>
    <fullName>Donor_ID__c</fullName>
    <formula>npsp__Primary_Contact__r.Donor_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Donor ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Donor_Name__c.field-meta.xml
<CustomField>
    <fullName>Donor_Name__c</fullName>
    <formula>IF(ISNULL(npsp__Primary_Contact__c), Account.Name,   npsp__Primary_Contact__r.LastName )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Donor Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Gift_Aid_Eligible_Status__c.field-meta.xml
<CustomField>
    <fullName>Gift_Aid_Eligible_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Gift Aid Status for this donation</description>
    <inlineHelpText>Gift Aid Status (Donation)</inlineHelpText>
    <label>Gift Aid Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Gift_Aid_Value__c.field-meta.xml
<CustomField>
    <fullName>Gift_Aid_Value__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>If the Donation is Submitted to HMRC portal, this Field will show the Submitted Gift Aid Value , else  Estimate Gift Aid Value</description>
    <formula>If(Gift_Aid_Submitted__c, Gift_Aid_Submitted_Value__c , Estimate_Gift_Aid_Value__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Estimate Gift Aid Value or Submitted Gift Aid Value</inlineHelpText>
    <label>Gift Aid Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <businessProcess>Donations</businessProcess>
    <description>Donations</description>
    <label>Donation</label>
</RecordType>

force-app/main/default/globalValueSets/Donation_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SD</fullName>
        <label>Single</label>
    </customValue>
    <customValue>
        <fullName>RD</fullName>
        <label>Recurring Monthly</label>
    </customValue>
    <customValue>
        <fullName>10N</fullName>
        <label>10 Nights</label>
    </customValue>
    <customValue>
        <fullName>RDA</fullName>
        <label>Recurring Annually</label>
    </customValue>
    <customValue>
        <fullName>WK</fullName>
        <label>Weekly</label>
    </customValue>
    <customValue>
        <fullName>30N</fullName>
        <label>30 Nights</label>
    </customValue>
    <customValue>
        <fullName>27N</fullName>
        <label>27 Night</label>
    </customValue>
    <customValue>
        <fullName>30D</fullName>
        <label>30 Days</label>
    </customValue>
    <customValue>
        <fullName>EMI</fullName>
    </customValue>
    <customValue>
        <fullName>10D</fullName>
    </customValue>
    <description>Donation Types</description>
    <masterLabel>Donation Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Yes_No.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <description>Yes/No</description>
    <masterLabel>Yes/No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Audit_2020_csv.cls
public class Audit_2020_csv {
    
    Map<Id,List<Income_Card_Payment_History__c>> OppMap2CardHistory = new Map<Id,List<Income_Card_Payment_History__c>>();
    Decimal TotalItemAmount = 0.00;
    Decimal CardAmount = 0.00;
    Integer b = 0;
    Integer c = 0;
    String csvData = 'Donation_Id,transactionDate,Item Name,Country,Stipulation,Program category,Donation name,Donation Amount,Item Amount,Total_Card_Amount,Individual_Card_Amount,CurrencyIsoCode,Gift Aid Declaration,Gift Aid Value,Stripe CH number,Donor Name,Donor ID';
    
    public Audit_2020_csv(){    
        for(Income_Card_Payment_History__c temp : [SELECT Amount__c,Id,Income_Card_Payment__c,Income_Card_Payment__r.Opportunity__c,Income_Card_Payment__r.Opportunity__r.Amount,Income_Card_Payment__r.Opportunity__r.Gift_Aid_Eligible_Status__c,Income_Card_Payment__r.Opportunity__r.Gift_Aid_Value__c,Income_Card_Payment__r.Opportunity__r.CurrencyIsoCode,Order_ID__c,Transaction_Date__c,Income_Card_Payment__r.Total_Amount_Taken__c,Income_Card_Payment__r.Opportunity__r.Name,CurrencyIsoCode,Income_Card_Payment__r.Opportunity__r.Donor_Name__c,Income_Card_Payment__r.Opportunity__r.Donor_ID__c FROM Income_Card_Payment_History__c Where  Amount__c>0 and Payment_Status__c !='Failed' and CreatedDate >= 2020-05-23T00:00:00z and CreatedDate <= 2020-05-30T23:59:59z]){
            CardAmount += temp.Amount__c;
            b++;
            List<Income_Card_Payment_History__c> tempList = (OppMap2CardHistory.keyset().contains(temp.Income_Card_Payment__r.Opportunity__c))?OppMap2CardHistory.get(temp.Income_Card_Payment__r.Opportunity__c): new List<Income_Card_Payment_History__c>();
            tempList.add(temp);   
            OppMap2CardHistory.put(temp.Income_Card_Payment__r.Opportunity__c,tempList);
        }
       
        
        
        for(npsp__Allocation__c alloc:[SELECT GAU_Name__c,npsp__Amount__c,npsp__Opportunity__r.Amount,npsp__Opportunity__r.Name,Country__c,npsp__Opportunity__c,npsp__General_Accounting_Unit__r.Stipulation__c ,npsp__Opportunity__r.CloseDate,npsp__Opportunity__r.Donation_Type__c,npsp__Opportunity__r.Gift_Aid_Value__c,npsp__Opportunity__r.CurrencyIsoCode,CurrencyIsoCode,npsp__Opportunity__r.Gift_Aid_Eligible_Status__c,npsp__General_Accounting_Unit__r.Programme_Category__c FROM npsp__Allocation__c Where npsp__Opportunity__c IN:OppMap2CardHistory.keyset() and npsp__Opportunity__c !=null ]){
            // Percentage of Item Amount with Donation Amount
            c++;           
            if(alloc.npsp__Amount__c != null){
                TotalItemAmount +=alloc.npsp__Amount__c;
                for(Income_Card_Payment_History__c tempCard:OppMap2CardHistory.get(alloc.npsp__Opportunity__c)){
                    //TotalCardAmount = Percentage Item Amount
                    csvData +='\n'+alloc.npsp__Opportunity__c+','+tempCard.Transaction_Date__c+','+alloc.GAU_Name__c+','+alloc.Country__c+','+alloc.npsp__General_Accounting_Unit__r.Stipulation__c+','+ alloc.npsp__General_Accounting_Unit__r.Programme_Category__c +','+tempCard.Income_Card_Payment__r.Opportunity__r.Name +','+alloc.npsp__Opportunity__r.Amount +','+alloc.npsp__Amount__c+','+tempCard.Income_Card_Payment__r.Total_Amount_Taken__c+','+ tempCard.Amount__c +','+alloc.CurrencyIsoCode+','+alloc.npsp__Opportunity__r.Gift_Aid_Eligible_Status__c+','+alloc.npsp__Opportunity__r.Gift_Aid_Value__c+','+tempCard.Order_ID__c+','+tempCard.Income_Card_Payment__r.Opportunity__r.Donor_Name__c+','+tempCard.Income_Card_Payment__r.Opportunity__r.Donor_ID__c;
        		}  
            }
            
        }
	
        System.debug(System.LoggingLevel.ERROR, 'times first query is run'+b);
        System.debug(System.LoggingLevel.ERROR, 'times second query is run'+c);
        System.debug(System.LoggingLevel.ERROR, 'Total OppMap2CardHistory Map Size ==>'+OppMap2CardHistory.size());
        System.debug(System.LoggingLevel.ERROR, 'testDuring');
        
        
        //System.debug('TotalItemAmount ==>'+TotalItemAmount);
        
        //System.debug('CardAmount ==>'+CardAmount);
        
        //Todo attach csvData to Attachment
        
        // Todo Verify Data (TotalItemAmount) and CardAmount => Compare Total History Amount with CSV item Amount
        Attachment att = new Attachment(Name='Audit_23_05_20__30_05_20_Data-'+System.now().format()+'.csv',Body=Blob.valueOf(csvData),parentId='0014J00000ZpT1FQAV');
        insert att;
		
    }
	@Future
    Public Static void MakeFutureCall(){
        Audit_2020_csv temp = new Audit_2020_csv();
        System.debug(System.LoggingLevel.ERROR, 'testAfter');
    }

}