force-app/main/default/objects/Account/fields/Donor_Id__c.field-meta.xml
<CustomField>
    <fullName>Donor_Id__c</fullName>
    <displayFormat>{00000}</displayFormat>
    <label>Donor Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Regional_Office_Code__c.field-meta.xml
<CustomField>
    <fullName>Regional_Office_Code__c</fullName>
    <label>Regional_Office_Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regional_Office_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Donor_ID__c.field-meta.xml
<CustomField>
    <fullName>Donor_ID__c</fullName>
    <description>Unique Donor ID - Country Code + 7 Digits (UK1234567)</description>
    <externalId>true</externalId>
    <label>Donor ID</label>
    <length>9</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Regional_Office_Code__c.field-meta.xml
<CustomField>
    <fullName>Regional_Office_Code__c</fullName>
    <label>Regional_Office_Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regional_Office_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Donor.recordType-meta.xml
<RecordType>
    <fullName>Donor</fullName>
    <active>true</active>
    <description>Donor Contact</description>
    <label>Donor</label>
</RecordType>

force-app/main/default/objects/Income_Direct_Debit__c/Income_Direct_Debit__c.object-meta.xml
<CustomObject>
    <label>Direct Debit Detail</label>
    <nameField>
        <displayFormat>DD{00000000}</displayFormat>
        <label>AUDDIS Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct Debit Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Income_Direct_Debit__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Income_Direct_Debit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>DD_Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>DD_Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Bank_Address__c.field-meta.xml
<CustomField>
    <fullName>DD_Bank_Address__c</fullName>
    <label>DD Bank Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Bank_City__c.field-meta.xml
<CustomField>
    <fullName>DD_Bank_City__c</fullName>
    <label>DD Bank City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Bank_Phone__c.field-meta.xml
<CustomField>
    <fullName>DD_Bank_Phone__c</fullName>
    <label>DD Bank Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Bank_Postcode__c.field-meta.xml
<CustomField>
    <fullName>DD_Bank_Postcode__c</fullName>
    <label>DD Bank Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Bank_Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>DD_Bank_Sort_Code__c</fullName>
    <label>Bank Sort Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Collection_Day__c.field-meta.xml
<CustomField>
    <fullName>DD_Collection_Day__c</fullName>
    <label>Collection Day</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DD_Collection_Period__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Collection_Period__c.field-meta.xml
<CustomField>
    <fullName>DD_Collection_Period__c</fullName>
    <label>Collection Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Collection_Reference__c.field-meta.xml
<CustomField>
    <fullName>DD_Collection_Reference__c</fullName>
    <defaultValue>&quot;Donation&quot;</defaultValue>
    <label>Collection Reference</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Collection_Stretch__c.field-meta.xml
<CustomField>
    <fullName>DD_Collection_Stretch__c</fullName>
    <label>Collection Stretch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Collection_Type__c.field-meta.xml
<CustomField>
    <fullName>DD_Collection_Type__c</fullName>
    <inlineHelpText>Fixed Collection type will not be collected after the End Date</inlineHelpText>
    <label>Collection Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
                <default>true</default>
                <label>Fixed</label>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>One Off</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_End_Date__c.field-meta.xml
<CustomField>
    <fullName>DD_End_Date__c</fullName>
    <inlineHelpText>DDs Will not be collected after this date</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_First_Collection_Amount__c.field-meta.xml
<CustomField>
    <fullName>DD_First_Collection_Amount__c</fullName>
    <label>First Collection Amount</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Last_Collection_Failed__c.field-meta.xml
<CustomField>
    <fullName>DD_Last_Collection_Failed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is Read only and set my the DD Engine</description>
    <inlineHelpText>This is Read only and set my the DD Engine</inlineHelpText>
    <label>Last Collection Failed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Single_Account_Holder__c.field-meta.xml
<CustomField>
    <fullName>DD_Single_Account_Holder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DD Single Account Holder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>DD_Start_Date__c</fullName>
    <inlineHelpText>DDs will not be collected before this date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Status__c.field-meta.xml
<CustomField>
    <fullName>DD_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Instruction</fullName>
                <default>true</default>
                <label>New Instruction</label>
            </value>
            <value>
                <fullName>First Collection</fullName>
            </value>
            <value>
                <fullName>Ongoing Collection</fullName>
            </value>
            <value>
                <fullName>Final Collection</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>First Represent</fullName>
            </value>
            <value>
                <fullName>Second Represent</fullName>
            </value>
            <value>
                <fullName>Third Represent</fullName>
            </value>
            <value>
                <fullName>Cancelled by Payer</fullName>
            </value>
            <value>
                <fullName>Cancelled by Originator</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Income_Direct_Debit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/Recurring_Donation__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Donation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurring Donation</label>
    <referenceTo>npe03__Recurring_Donation__c</referenceTo>
    <relationshipLabel>Direct Debit Details</relationshipLabel>
    <relationshipName>Direct_Debit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SmarterPay_Direct_Debit_Settings__c/SmarterPay_Direct_Debit_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SmarterPay Direct Debit Settings</label>
</CustomObject>

force-app/main/default/objects/SmarterPay_Direct_Debit_Settings__c/fields/Bank_Account_Checker_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Checker_Endpoint__c</fullName>
    <label>Bank Account Checker Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SmarterPay_Payment_Config__c/SmarterPay_Payment_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SmarterPay Payment Config</label>
</CustomObject>

force-app/main/default/objects/SmarterPay_Payment_Config__c/fields/SmarterPay_User_Name__c.field-meta.xml
<CustomField>
    <fullName>SmarterPay_User_Name__c</fullName>
    <label>SmarterPay User Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SmarterPay_Payment_Config__c/fields/Standard_Authenticate_Capture_Ecommerce__c.field-meta.xml
<CustomField>
    <fullName>Standard_Authenticate_Capture_Ecommerce__c</fullName>
    <label>Standard Authenticate Capture Ecommerce</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SmarterPay_Payment_Config__c/fields/Standard_Authenticate_Capture_MOTO__c.field-meta.xml
<CustomField>
    <fullName>Standard_Authenticate_Capture_MOTO__c</fullName>
    <label>Standard Authenticate Capture MOTO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SmarterPay_Payment_Config__c/fields/Standard_Authenticate_Release__c.field-meta.xml
<CustomField>
    <fullName>Standard_Authenticate_Release__c</fullName>
    <label>Standard Authenticate Release</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SmarterPay_Payment_Config__c/fields/Standard_Deferred_Capture_Ecommerce__c.field-meta.xml
<CustomField>
    <fullName>Standard_Deferred_Capture_Ecommerce__c</fullName>
    <label>Standard Deferred Capture Ecommerce</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SmarterPay_Payment_Config__c/fields/Standard_Deferred_Capture_MOTO__c.field-meta.xml
<CustomField>
    <fullName>Standard_Deferred_Capture_MOTO__c</fullName>
    <label>Standard Deferred Capture MOTO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SmarterPay_Payment_Config__c/fields/Standard_Deferred_Release__c.field-meta.xml
<CustomField>
    <fullName>Standard_Deferred_Release__c</fullName>
    <label>Standard Deferred Release</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SmarterPay_Payment_Config__c/fields/Standard_Ecommerce__c.field-meta.xml
<CustomField>
    <fullName>Standard_Ecommerce__c</fullName>
    <label>Standard Ecommerce</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SmarterPay_Payment_Config__c/fields/Standard_MOTO__c.field-meta.xml
<CustomField>
    <fullName>Standard_MOTO__c</fullName>
    <label>Standard MOTO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SmarterPay_Payment_Config__c/fields/Standard_Refund__c.field-meta.xml
<CustomField>
    <fullName>Standard_Refund__c</fullName>
    <label>Standard Refund</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SmarterPay_Payment_Config__c/fields/Standard_Repeat__c.field-meta.xml
<CustomField>
    <fullName>Standard_Repeat__c</fullName>
    <label>Standard Repeat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TriggerSettings__c/fields/Card_Payment_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Card_Payment_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Card Payment Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSettings__c/fields/Direct_Debit_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Direct_Debit_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Direct Debit Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Regional_Office_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>US</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>Regional_Office_Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SMPRenewWizardControllerTest.cls
@isTest
public inherited sharing class SMPRenewWizardControllerTest {
  
    @testSetup
     static void CreateTestFrameWork()
    {
        TriggerSettings__c triggerSetting = new TriggerSettings__c();
        triggerSetting.Card_Payment_Trigger__c = false;
        triggerSetting.Direct_Debit_Trigger__c = false;

        insert triggerSetting;
		SmarterPay_Direct_Debit_Settings__c config = new SmarterPay_Direct_Debit_Settings__c(Bank_Account_Checker_Endpoint__c = 'www.test.com',
        User_Id__c = '123456');
        insert config;
        
        SmarterPay_Payment_Config__c paymentConfig = new SmarterPay_Payment_Config__c();
        paymentConfig.APIKey__c = '123456';
        paymentConfig.SmarterPay_User_Name__c = 'test';
    
        paymentConfig.Standard_MOTO__c = '/MOTO';
        paymentConfig.Standard_Ecommerce__c = '/Ecommerce';
        paymentConfig.Standard_Repeat__c = '/Repeat';
        paymentConfig.Standard_Refund__c = '/Refund';
        paymentConfig.Standard_Deferred_Capture_MOTO__c = '/DeferredCaptureMOTO';
        paymentConfig.Standard_Deferred_Capture_Ecommerce__c = '/DeferredCaptureEcommerce';
        paymentConfig.Standard_Deferred_Release__c = '/DeferredRelease'; 
        paymentConfig.Standard_Authenticate_Capture_MOTO__c = '/AuthenticateCaptureMOTO'; 
        paymentConfig.Standard_Authenticate_Capture_Ecommerce__c = '/AuthenticateCaptureEcommerce'; 
        paymentConfig.Standard_Authenticate_Release__c = '/AuthenticateRelease';

        insert paymentConfig;

        Contact contact = new Contact(
            LastName = 'Test',
            Donor_ID__c = 'UK0188921',                                           // Donor ID
            npe01__PreferredPhone__c = 'Mobile',                                 // Preferred Phone
            Email = 'salma_93@hotmail.co.uk',                                    // Email
            MobilePhone = '07740030241',                                         // Mobile
            npe01__WorkPhone__c = '07740030241',                           // Work Phone
            MailingStreet = 'Test',
            MailingCity = 'Test',
            MailingCountry = 'Test',
            MailingPostalCode = 'Test'
            );
        insert contact;

        npe03__Recurring_Donation__c donation = new npe03__Recurring_Donation__c(
            npsp__RecurringType__c = 'Open',                         // Recurring Type
            npe03__Amount__c = 40.00,                                  // Amount
            npe03__Installment_Period__c = 'Monthly',                  // Installment Period
            npsp__InstallmentFrequency__c = 1,                       // Installment Frequency
            npsp__Day_of_Month__c = '1',                               // Day of Month
            npsp__StartDate__c = Date.today(),                         // Effective Date
            npe03__Next_Payment_Date__c = Date.today(),                // Next Donation Date
            npsp__PaymentMethod__c = 'Direct Debit',                   // Payment Method
            npe03__Contact__c = contact.Id,                     // Contact
            npe03__Date_Established__c = Date.today(),                 // Date Established
            npsp__Status__c = 'Active',
			Regional_office_code__c = 'UK'                                // Status
          );
          insert donation;
    }
    @isTest static void testGetRecurringDonation() 
    {
        Test.startTest();
        Id donationID = [SELECT Id,Regional_Office_code__c FROM npe03__Recurring_Donation__c limit 1]?.Id;
        npe03__Recurring_Donation__c result = SMPRenewWizardController.getRecurringDonation(donationID);
		
        System.assertEquals(donationID, result.Id);
        Test.stopTest();
    }
   
    @isTest static void testSaveDirectDebitWithoutCurrentDirectDebit() 
    {
 

        npe03__Recurring_Donation__c donation = [SELECT Id, npe03__Amount__c, Opportunity__c, Direct_Debit_Detail__c, npe03__Contact__c,Regional_Office_code__c FROM npe03__Recurring_Donation__c limit 1];
        
        Income_Direct_Debit__c dd = new Income_Direct_Debit__c(
            Recurring_Donation__c = donation.Id,
            DD_Bank_Address__c = 'P.O. Box 8888, Nationwide Hse, Pipers Way',// DD Bank Address
            DD_Bank_City__c = 'Swindon L',                                     // DD Bank City
            DD_Bank_Postcode__c = 'SN38 1NW',                                  // DD Bank Postcode
            DD_Bank_Phone__c = '0800 302011',                                  // DD Bank Phone
            DD_Single_Account_Holder__c = false,                               // DD Single Account Holder
            DD_Status__c = 'Cancelled',                                        // Status
            DD_Collection_Day__c = '1',                                        // Collection Day
            DD_Bank_Sort_Code__c = '074456',                                   // Bank Sort Code
            DD_Collection_Period__c = 'Monthly',                               // Collection Period
            DD_Bank_Account_Number__c = '11104102',                            // Bank Account Number
            DD_Collection_Stretch__c = '1',                                    // Collection Stretch
            DD_Bank_Account_Name__c = 'Name',                                  // Bank Account Name
            DD_Collection_Type__c = 'Fixed',                                   // Collection Type
            DD_First_Collection_Amount__c = 40.00,                             // First Collection Amount
            DD_Collection_Reference__c = 'Donation',                           // Collection Reference
            DD_Last_Collection_Failed__c = false,                              // Last Collection Failed
            DD_Start_Date__c = Date.today(),                     // Start Date
            DD_End_Date__c = Date.today()                       // End Date

        );
        String responseBody = '{"ProcessNewDDFirstCollectionDateResult":{"FirstCollectionDate":"11/05/2017","Error":""}}';
        HttpRestCallOutMock fakeResponse = new HttpRestCallOutMock(200, responseBody);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        Test.startTest();
        SMPRenewWizardController.saveDirectDebit(dd, donation);
        Test.stopTest();

        dd = [SELECT Id, DD_Status__c, DD_First_Collection_Amount__c, Contact__c FROM Income_Direct_Debit__c];
        System.debug('#### dd: ' + dd);
        donation = [SELECT Id, npe03__Amount__c, Opportunity__c, Direct_Debit_Detail__c, npe03__Contact__c,Regional_Office_code__c FROM npe03__Recurring_Donation__c];

        System.assertNotEquals(null, dd.Id);
        System.assertEquals('New Instruction', dd.DD_Status__c);
        System.assertEquals(40.00, dd.DD_First_Collection_Amount__c);
        System.assertEquals(dd.Id, donation.Direct_Debit_Detail__c);
    }
    @isTest
    private static void modulusCheckDirectDebitDateTest() 
    {
        
        String sortCode = '074456';
        String accountNumber = '11104102';

        Income_Direct_Debit__c dd = new Income_Direct_Debit__c();

        dd.DD_Bank_Sort_Code__c = sortCode;
        dd.DD_Bank_Account_Number__c = accountNumber;

        Test.startTest();
        
        Income_Direct_Debit__c response = SMPRenewWizardController.modulusCheckDirectDebit(dd);
	
        System.assertEquals(false, response.DD_Account_Number_OK__c);
        System.assertEquals(false, response.DD_Sort_Code_OK__c);
        Test.stopTest();
    }
    @isTest static void testGetAuthPaymentURL() 
    {
       
        npe03__Recurring_Donation__c donation = [SELECT Id, Name, npe03__Amount__c, npe03__Contact__c, Opportunity__c, Direct_Debit_Detail__c, npe03__Contact__r.FirstName, npe03__Contact__r.LastName,
                                                    npe03__Contact__r.MailingStreet, npe03__Contact__r.MailingCity, CurrencyIsoCode,
                                                    npe03__Contact__r.MailingState, npe03__Contact__r.MailingPostalCode,
                                                    npe03__Contact__r.MailingCountry, npe03__Contact__r.Email,Regional_Office_code__c 
                                                    FROM npe03__Recurring_Donation__c];
		Test.startTest();

        System.assert(SMPRenewWizardController.getAuthPaymentURL(donation).contains('AuthenticateCaptureMOTO'));
        Test.stopTest();
    }
}