force-app/main/default/objects/Basket__c/Basket__c.object-meta.xml
<CustomObject>
    <label>Basket</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Basket #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Basket</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Basket__c/fields/Basket_Details__c.field-meta.xml
<CustomField>
    <fullName>Basket_Details__c</fullName>
    <description>Basket Details</description>
    <label>Basket Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Basket__c/fields/Basket_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Basket_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Checkout Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Basket__c/fields/Basket_Source__c.field-meta.xml
<CustomField>
    <fullName>Basket_Source__c</fullName>
    <label>Basket Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>MyAccount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Basket__c/fields/BasketId__c.field-meta.xml
<CustomField>
    <fullName>BasketId__c</fullName>
    <label>BasketId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Basket__c/fields/Donation_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Donation_Date_Time__c</fullName>
    <label>Donation Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Basket__c/fields/Donor_Details__c.field-meta.xml
<CustomField>
    <fullName>Donor_Details__c</fullName>
    <label>Donor Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Basket__c/fields/Payment_Details__c.field-meta.xml
<CustomField>
    <fullName>Payment_Details__c</fullName>
    <label>Payment Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Basket__c/fields/Regional_Office_Code__c.field-meta.xml
<CustomField>
    <fullName>Regional_Office_Code__c</fullName>
    <label>Regional Office Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regional_Office_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Basket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Awaiting Payment Details</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>In Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Regional_Office_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>US</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>Regional_Office_Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/donationAPI.cls
@RestResource(urlMapping='/donation/v1/*')
global without Sharing class donationAPI {
    @HttpPost
    global static void doPost(){
       List<Basket__c > donationsToInsert = new List<Basket__c>();
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;
        
        try{
           
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            Map<String,Object> request =(Map<String,Object>)JSON.deserializeUntyped(req.requestBody.toString());
            List<Object> newDonationList = (List<Object>)request.values()[0];
            for(Object obj:newDonationList){
                Basket__c temp = new Basket__c();
                Map<String,Object> tempMap = (Map<String,Object>)obj;
                List<Object> baskestDetails = (List<Object>)tempMap.values()[0];
                Map<String,Object> baskestDetailsMap = (Map<String,Object>)baskestDetails[0];
                temp.Donor_Details__c = JSON.serialize(baskestDetailsMap.get('Supporter'), true);
                Map<String,Object> baskestgroupMap  = (Map<String,Object>)baskestDetailsMap.get('Basket');
                temp.CurrencyIsoCode = String.valueOf(baskestgroupMap.get('CurrencyISOCode'));
                temp.Basket_Details__c = JSON.serialize(baskestDetailsMap.get('Basket'), true);
                temp.Payment_Details__c = JSON.serialize(baskestDetailsMap.get('PaymentMethods'), true);
                //Todo Change API Name of the feild Basket_External_Id__c => CheckoutId__c
                temp.Basket_External_Id__c = String.valueOf(baskestDetailsMap.get('CheckoutId'));
                
                temp.BasketId__c = String.valueOf(baskestDetailsMap.get('BasketId'));
                temp.Status__c = String.valueOf(baskestDetailsMap.get('Status'));
                String transactionTimeUtc = baskestDetailsMap.get('TransactionTimeUtc').toString();
                temp.Donation_Date_Time__c = DateTime.valueOf(transactionTimeUtc.replace('T', ' '));
                temp.Regional_Office_Code__c = String.valueOf(baskestDetailsMap.get('SiteCode'));
                temp.Basket_Source__c = 'Website';
                donationsToInsert.add(temp);
            }
            if(donationsToInsert.size()>0)
                upsert donationsToInsert Basket_External_Id__c;
            gen.writeFieldName('JsonResponse');
            gen.writeStartArray();
            for(Basket__c d:donationsToInsert){
                gen.writeStartObject();
                    gen.writeStringField('BasketId', d.Basket_External_Id__c);
                    gen.writeStringField('DonationId', d.Id);
                gen.writeEndObject();
            }
            gen.writeEndArray();
            gen.writeBooleanField ('IsError', false);
            gen.writeStringField('ErrorMessage', '');
            gen.writeStringField ('HttpResponseCode ', 'OK');
            gen.writeEndObject();
            gen.close();
            res.responseBody = Blob.valueOf(gen.getAsString());

        }catch(Exception ex){
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeBooleanField ('IsError', true);
            gen.writeStringField('ErrorMessage', ex.getMessage()+'-'+ex.getStackTraceString());
            gen.writeStringField ('HttpResponseCode ', 'Redirect');
            gen.writeEndObject();
            gen.close();
            res.statusCode = 417;
            res.responseBody = Blob.valueOf(gen.getAsString());
        }
        
         
        
        
        
        
    }
}