force-app/main/default/objects/Basket__c/Basket__c.object-meta.xml
<CustomObject>
    <label>Basket</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Basket #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Basket</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Basket__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>My_Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Basket__c/fields/Regional_Office_Code__c.field-meta.xml
<CustomField>
    <fullName>Regional_Office_Code__c</fullName>
    <label>Regional Office Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regional_Office_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Regional_Office_Code__c.field-meta.xml
<CustomField>
    <fullName>Regional_Office_Code__c</fullName>
    <label>Regional_Office_Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regional_Office_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/HA_Payment_Schedule__c/HA_Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Payment Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HA_Payment_Schedule__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every Other Night</fullName>
            </value>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/Income_Card_Payment__c.object-meta.xml
<CustomObject>
    <description>Smarter Pay - Card Payment Detail</description>
    <label>Card Payment Detail</label>
    <nameField>
        <displayFormat>HUAPP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Income_Card_Payment__c/fields/Basket__c.field-meta.xml
<CustomField>
    <fullName>Basket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Basket</label>
    <referenceTo>Basket__c</referenceTo>
    <relationshipLabel>Card Payment Details</relationshipLabel>
    <relationshipName>Card_Payment_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Income_Card_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Customer_Payment_Description__c.field-meta.xml
<CustomField>
    <fullName>Customer_Payment_Description__c</fullName>
    <label>Customer Payment Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Gateway_Customer_Reference__c.field-meta.xml
<CustomField>
    <fullName>Gateway_Customer_Reference__c</fullName>
    <label>Gateway Customer Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Internal_Payment_Description__c.field-meta.xml
<CustomField>
    <fullName>Internal_Payment_Description__c</fullName>
    <label>Internal Payment Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Income_Card_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Payment_Method_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method_Id__c</fullName>
    <externalId>true</externalId>
    <label>Payment Method Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Recurring_Donation__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Donation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurring Donation</label>
    <referenceTo>npe03__Recurring_Donation__c</referenceTo>
    <relationshipLabel>Card Payment Details</relationshipLabel>
    <relationshipName>Card_Payment_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Source_Card_Payment__c.field-meta.xml
<CustomField>
    <fullName>Source_Card_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Card Payment</label>
    <referenceTo>Income_Card_Payment__c</referenceTo>
    <relationshipLabel>Card Payment Details</relationshipLabel>
    <relationshipName>Card_Payment_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Full Refund</fullName>
            </value>
            <value>
                <fullName>Partial Refund</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Deferred_Released</fullName>
                <label>Deferred Released</label>
            </value>
            <value>
                <fullName>Deferred_Aborted</fullName>
                <label>Deferred Aborted</label>
            </value>
            <value>
                <fullName>Authenticate</fullName>
            </value>
            <value>
                <fullName>Authorised</fullName>
            </value>
            <value>
                <fullName>Authorised &amp; First Collection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Card_Payment_History__c/Income_Card_Payment_History__c.object-meta.xml
<CustomObject>
    <label>Card Payment History</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Income Card Payment History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Income_Card_Payment_History__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment_History__c/fields/Customer_Payment_Description__c.field-meta.xml
<CustomField>
    <fullName>Customer_Payment_Description__c</fullName>
    <label>Customer Payment Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment_History__c/fields/Income_Card_Payment__c.field-meta.xml
<CustomField>
    <fullName>Income_Card_Payment__c</fullName>
    <label>Income Card Payment</label>
    <referenceTo>Income_Card_Payment__c</referenceTo>
    <relationshipName>Income_Card_Payment_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment_History__c/fields/Internal_Payment_Description__c.field-meta.xml
<CustomField>
    <fullName>Internal_Payment_Description__c</fullName>
    <label>Internal Payment Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment_History__c/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Schedule</label>
    <referenceTo>Payment_Schedule__c</referenceTo>
    <relationshipName>Income_Card_Payment_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment_History__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <label>Transaction Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment_History__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Deferred Released</fullName>
            </value>
            <value>
                <fullName>Deferred Aborted</fullName>
            </value>
            <value>
                <fullName>Authenticate</fullName>
            </value>
            <value>
                <fullName>Authorised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Basket__c.field-meta.xml
<CustomField>
    <fullName>Basket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Basket</label>
    <referenceTo>Basket__c</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DonationCode__c.field-meta.xml
<CustomField>
    <fullName>DonationCode__c</fullName>
    <formula>Text(Payment_Schedule__r.Code__c)</formula>
    <label>Donation Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <description>Used for bulk upload process</description>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Schedule</label>
    <referenceTo>HA_Payment_Schedule__c</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Regional_Office_Code__c.field-meta.xml
<CustomField>
    <fullName>Regional_Office_Code__c</fullName>
    <label>Regional_Office_Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regional_Office_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Deprecated Payment Schedule</label>
    <nameField>
        <displayFormat>PSN-{0}</displayFormat>
        <label>Payment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deprecated Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Schedule__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Payment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Regional_Office_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>US</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>Regional_Office_Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TriggerHandler_CardPayment.cls
/**
* @description       : 
* @author            : Iamsfdeveloper
* @group             : 
* @last modified on  : 01-12-2022
* @last modified by  : Iamsfdeveloper
**/
public without sharing class TriggerHandler_CardPayment {
    public static void OnBeforeInsert(List<Income_Card_Payment__c> newRecords)
    {
    }
    
    public static void OnAfterInsert(Map<Id, Income_Card_Payment__c> newRecords){  
        Set<Id> cardPaymentIds = new Set<Id>();
        List<Opportunity> updateOpportunities = new List<Opportunity>();
        List<npe01__OppPayment__c> paymentsToUpdate = new List<npe01__OppPayment__c>();
        Map<Id,Id> InternalWizardIdsOppMap = new Map<Id,Id>();
        set<Id> basketIds = new set<Id>();
        for(Income_Card_Payment__c card : [Select Id,Payment_Reference__c,Basket__c,Transaction_Type__c,Payment_Status__c,Payment_Method_Id__c,Opportunity__c,Contact__r.Regional_Office_code__c,Gateway_Customer_Reference__c,Opportunity__r.Regional_office_code__c,Opportunity__r.DonationCode__c From Income_Card_Payment__c Where Id IN: newRecords.Keyset()])
        {
            
            if(card.Payment_Method_Id__c == null  &&  card.Gateway_Customer_Reference__c != null && (card.Opportunity__c != null || card.Recurring_Donation__c != null)){
                //Retrieve Card Payment Method Id
                cardPaymentIds.add(card.Id);
            }else if(card.Payment_Method_Id__c != null  && card.Basket__c != null && (card.Transaction_Type__c =='Authenticate' || card.Transaction_Type__c =='Sale'  || card.Transaction_Type__c =='Authorised')  && (card.Payment_Status__c =='succeeded' || card.Payment_Status__c =='Successful' || card.Payment_Status__c =='setup') ){
                basketIds.add(card.Basket__c) ;  
                
            }
            else if(card.payment_Reference__c =='InternalWizard' && card.Payment_Method_Id__c != null  && card.Opportunity__c != null &&  (card.Transaction_Type__c =='Authenticate' || card.Transaction_Type__c =='Sale'  || card.Transaction_Type__c =='Authorised')  && (card.Payment_Status__c =='succeeded' || card.Payment_Status__c =='Successful' || card.Payment_Status__c =='setup') ){
                updateOpportunities.add(new Opportunity(Id=card.Opportunity__c,Payment_Method__c ='Card Payment',StageName = 'Setup Completed')) ;  
                InternalWizardIdsOppMap.put(card.Opportunity__c,card.Id);
                
            }
        }
        System.debug('basketIds=>'+basketIds);
        if(basketIds.size()>0)
            for(Opportunity opp:[Select Id,StageName,Payment_Method__c FROM Opportunity Where Basket__c IN: basketIds and DonationCode__c  IN ('10N','30N','10D') and StageName='Awaiting Payment Details']){
                opp.Payment_Method__c ='Card Payment';
                opp.StageName = 'Setup Completed';
                updateOpportunities.add(opp);
            }
        if(cardPaymentIds.size()>0 && !System.isFuture())
            CardConfiguration.getCustomerPaymentMethod(cardPaymentIds);
        if(updateOpportunities.size()>0){
            upsert updateOpportunities;
        }
        if(InternalWizardIdsOppMap.size()>0){
            for(npe01__OppPayment__c payment : [Select Id,Card_Details__c,npe01__Opportunity__c,npe01__Paid__c FROM npe01__OppPayment__c Where npe01__Paid__c = false and npe01__Opportunity__c IN:InternalWizardIdsOppMap.keyset() and (npe01__Opportunity__r.DonationCode__c ='30N' OR npe01__Opportunity__r.DonationCode__c ='10N' OR npe01__Opportunity__r.DonationCode__c ='10D')]){
                payment.Card_Details__c = InternalWizardIdsOppMap.get(payment.npe01__Opportunity__c);
                paymentsToUpdate.add(payment);
            }
        }
        if(paymentsToUpdate.size()>0)
            update paymentsToUpdate;
    }
    
    public static void OnBeforeUpdate(Map<Id, Income_Card_Payment__c> newRecords, Map<Id, Income_Card_Payment__c> oldRecords)
    {
        
    }
    
    public static void OnAfterUpdate(Map<Id, Income_Card_Payment__c> newRecords, Map<Id, Income_Card_Payment__c> oldRecords)
    {        
        List<npe03__Recurring_Donation__c> recurringDonations = new List<npe03__Recurring_Donation__c>();
        
        List<Income_Card_Payment__c> clonedCardPayment = new List<Income_Card_Payment__c>();
        List<Income_Card_Payment_History__c> clonedHistories = new List<Income_Card_Payment_History__c>();
        Set<String> oppIds = new Set<String>();
        Set<Id> cardPaymentIds = new Set<Id>();
        for(Income_Card_Payment__c card : newRecords.values())
        {
            if(card.Customer_Payment_Description__c  == 'Renewal' && card.Internal_Payment_Description__c != null && card.Internal_Payment_Description__c.startsWithIgnoreCase('a09'))
            {
                recurringDonations.add(new npe03__Recurring_Donation__c(Id = card.Internal_Payment_Description__c, Card_Payment_Detail__c = card.Id));
            }
            if(card.Payment_Method_Id__c == null  &&  card.Gateway_Customer_Reference__c != null && (card.Opportunity__c != null || card.Recurring_Donation__c != null)){
                //Retrieve Card Payment Method Id
                cardPaymentIds.add(card.Id);  
            }else if( card.Payment_Status__c == 'Successful'  && oldRecords.get(card.Id).Payment_Status__c != 'Successful' && (card.Transaction_Type__c == 'Sale' || card.Transaction_Type__c == 'Authenticate')){
                 
                    if(card.Opportunity__c != null)
                    {
                        oppIds.add(card.Opportunity__c);
                    } 
                    
                    if(String.isNotBlank(card.Internal_Payment_Description__c))
                    {
                        List<String> additionalOpportunityIds = card.Internal_Payment_Description__c.split(',');
                        
                        for(String s : additionalOpportunityIds)
                        {
                            if (s instanceOf Id)
                            {
                                oppIds.add(s);
                                Income_Card_Payment__c clone = card.clone();
                                clone.Opportunity__c = s;
                                clone.Source_Card_Payment__c = card.Id;
                                clonedCardPayment.add(clone);
                            }
                        }
                    }
                }
                
            
        }
        if(cardPaymentIds.size()>0){
            If(!System.isFuture())
            CardConfiguration.getCustomerPaymentMethod(cardPaymentIds);
       		// else
            //CardConfiguration.getCustomerPaymentMethodNonFuture(cardPaymentIds);
        }
        if(recurringDonations.size() > 0)
        {
            update recurringDonations;
        }
        
        if(oppIds.Size() > 0)
        {
            Map<Id, Opportunity> opportunities = new Map<Id, Opportunity>([SELECT Id, Amount, StageName, Payment_Schedule__r.Frequency__c FROM Opportunity WHERE Id IN :oppIds]);
            
            if(clonedCardPayment.Size() > 0)
            {
                insert clonedCardPayment;
                
                for(Income_Card_Payment__c payment : clonedCardPayment)
                {
                    Opportunity opp = opportunities.get(payment.Opportunity__c);
                    
                    Income_Card_Payment_History__c clone = new Income_Card_Payment_History__c();
                    clone.CurrencyIsoCode = payment.CurrencyIsoCode;
                    clone.Income_Card_Payment__c = payment.Id;
                    clone.Payment_Status__c = 'Successful';                
                    clone.Transaction_Date__c = DateTime.now();
                    
                    if(opp.Payment_Schedule__r.Frequency__c == 'Single')
                    {
                        clone.Transaction_Type__c = 'Sale';
                        clone.Amount__c = opp.Amount;
                    }
                    else
                    {
                        // Must be a recurring payment schedule
                        clone.Transaction_Type__c = 'Authenticate';
                        clone.Amount__c = 0.00;
                    }
                    
                    clonedHistories.add(clone);
                }
                
                if(clonedHistories.Size() > 0)
                {
                    insert clonedHistories;
                }
            }
        }        
    }
}