force-app/main/default/objects/Income_Direct_Debit__c/Income_Direct_Debit__c.object-meta.xml
<CustomObject>
    <label>Direct Debit Detail</label>
    <nameField>
        <displayFormat>DD{00000000}</displayFormat>
        <label>AUDDIS Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct Debit Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Account_Number_OK__c.field-meta.xml
<CustomField>
    <fullName>DD_Account_Number_OK__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account Number OK</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_First_Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>DD_First_Collection_Date__c</fullName>
    <inlineHelpText>This is set by the DD collection engine</inlineHelpText>
    <label>First Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_OK__c.field-meta.xml
<CustomField>
    <fullName>DD_OK__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DD OK</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Sort_Code_OK__c.field-meta.xml
<CustomField>
    <fullName>DD_Sort_Code_OK__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sort Code OK</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Status__c.field-meta.xml
<CustomField>
    <fullName>DD_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Instruction</fullName>
                <default>true</default>
                <label>New Instruction</label>
            </value>
            <value>
                <fullName>First Collection</fullName>
            </value>
            <value>
                <fullName>Ongoing Collection</fullName>
            </value>
            <value>
                <fullName>Final Collection</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>First Represent</fullName>
            </value>
            <value>
                <fullName>Second Represent</fullName>
            </value>
            <value>
                <fullName>Third Represent</fullName>
            </value>
            <value>
                <fullName>Cancelled by Payer</fullName>
            </value>
            <value>
                <fullName>Cancelled by Originator</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Income_Direct_Debit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/Recurring_Donation__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Donation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurring Donation</label>
    <referenceTo>npe03__Recurring_Donation__c</referenceTo>
    <relationshipLabel>Direct Debit Details</relationshipLabel>
    <relationshipName>Direct_Debit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <description>Used for bulk upload process</description>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TriggerHandler_DirectDebit.cls
/**
 * @description       : 
 * @author            : Iamsfdeveloper
 * @group             : 
 * @last modified on  : 01-12-2022
 * @last modified by  : Iamsfdeveloper
**/
public without sharing class TriggerHandler_DirectDebit {
    public static void OnBeforeInsert(List<Income_Direct_Debit__c> newRecords)
    {
        
    }

    public static void OnAfterInsert(Map<Id, Income_Direct_Debit__c> newRecords)
    {
        Set<Id> ddIds = new Set<Id>();
		List<Opportunity> opportunities = new List<Opportunity>();
        for(Income_Direct_Debit__c dd : newRecords.values())
        {
            if(dd.Opportunity__c != null && dd.Recurring_Donation__c == null){
                IF(dd.DD_First_Collection_Date__c != null)
                {
                    opportunities.add(new Opportunity(Payment_Method__c ='Direct Debit',Id=dd.Opportunity__c,StageName = (dd.DD_Status__c  =='New Instruction' && dd.DD_Sort_Code_OK__c && dd.DD_OK__c && dd.DD_Account_Number_OK__c)?'Paid':'In Payment Processing'));
                }else{
                    ddIds.add(dd.Id);
                }
            }
        }

        if(opportunities.Size() > 0)
        {
             update opportunities;
                        
        }    
        //Future Method for web callout to get Collection Dates
        //For Direct Debits From checkoutv4
        if(ddIds.size()>0)
            DirectDebitConfiguartion.updateCollectionDate(ddIds);
           
    }

    public static void OnBeforeUpdate(Map<Id, Income_Direct_Debit__c> newRecords, Map<Id, Income_Direct_Debit__c> oldRecords)
    {
    }
    
    public static void OnAfterUpdate(Map<Id, Income_Direct_Debit__c> newRecords, Map<Id, Income_Direct_Debit__c> oldRecords)
    {
         Set<Id> oppIds = new Set<Id>();
		List<Opportunity> opportunities = new List<Opportunity>();
        for(Income_Direct_Debit__c dd : [Select Id,DD_Status__c,Opportunity__c ,Recurring_Donation__c,DD_Sort_Code_OK__c,DD_OK__c,DD_Account_Number_OK__c FROM Income_Direct_Debit__c Where Id IN: newRecords.keyset() and Opportunity__r.StageName Not In ('Paid','In Payment Processing') AND DD_First_Collection_Date__c != null])
        {
            if(dd.Opportunity__c != null && dd.Recurring_Donation__c == null)
            {
                opportunities.add(new Opportunity(Payment_Method__c ='Direct Debit',Id=dd.Opportunity__c,StageName = (dd.DD_Status__c  =='New Instruction' && dd.DD_Sort_Code_OK__c && dd.DD_OK__c && dd.DD_Account_Number_OK__c)?'Paid':'In Payment Processing'));
            }
        }

        if(opportunities.Size() > 0)
        {
             update opportunities;
                        
        }    
    }
}