force-app/main/default/objects/Income_Direct_Debit__c/Income_Direct_Debit__c.object-meta.xml
<CustomObject>
    <label>Direct Debit Detail</label>
    <nameField>
        <displayFormat>DD{00000000}</displayFormat>
        <label>AUDDIS Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct Debit Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Collection_Day__c.field-meta.xml
<CustomField>
    <fullName>DD_Collection_Day__c</fullName>
    <label>Collection Day</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DD_Collection_Period__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Collection_Period__c.field-meta.xml
<CustomField>
    <fullName>DD_Collection_Period__c</fullName>
    <label>Collection Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Collection_Stretch__c.field-meta.xml
<CustomField>
    <fullName>DD_Collection_Stretch__c</fullName>
    <label>Collection Stretch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_First_Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>DD_First_Collection_Date__c</fullName>
    <inlineHelpText>This is set by the DD collection engine</inlineHelpText>
    <label>First Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Next_Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>DD_Next_Collection_Date__c</fullName>
    <inlineHelpText>This is set by the DD Collection Engine</inlineHelpText>
    <label>Next Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>DD_Start_Date__c</fullName>
    <inlineHelpText>DDs will not be collected before this date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Status__c.field-meta.xml
<CustomField>
    <fullName>DD_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Instruction</fullName>
                <default>true</default>
                <label>New Instruction</label>
            </value>
            <value>
                <fullName>First Collection</fullName>
            </value>
            <value>
                <fullName>Ongoing Collection</fullName>
            </value>
            <value>
                <fullName>Final Collection</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>First Represent</fullName>
            </value>
            <value>
                <fullName>Second Represent</fullName>
            </value>
            <value>
                <fullName>Third Represent</fullName>
            </value>
            <value>
                <fullName>Cancelled by Payer</fullName>
            </value>
            <value>
                <fullName>Cancelled by Originator</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/Failed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Failed_Reason__c</fullName>
    <inlineHelpText>Callout Failed Reason</inlineHelpText>
    <label>Failed Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SmarterPay_Direct_Debit_Settings__c/SmarterPay_Direct_Debit_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SmarterPay Direct Debit Settings</label>
</CustomObject>

force-app/main/default/objects/SmarterPay_Direct_Debit_Settings__c/fields/Calculate_Next_Collection_Date_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Calculate_Next_Collection_Date_Endpoint__c</fullName>
    <label>Calculate Next Collection Date Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DirectDebitConfiguartion.cls
/**
 * @description       : 
 * @author            : Iamsfdeveloper
 * @group             : 
 * @last modified on  : 12-22-2021
 * @last modified by  : Iamsfdeveloper
**/
public with sharing class DirectDebitConfiguartion {
    public final static string WAIT_PEROID_NEW_INSTRUCTION = '5';
    public static final String MESSAGE_CALLOUTERROR = 'Error Calling SmarterPay Service.';    
    public static SmarterPay_Direct_Debit_Settings__c directDebitConfig = SmarterPay_Direct_Debit_Settings__c.getInstance();
    @Future(callout=true)
    public static void updateCollectionDate(set<Id> newRecordIds){
        List<Income_Direct_Debit__c> newRecords = [SELECT Id,DD_Next_Collection_Date__c,DD_First_Collection_Date__c,DD_Collection_Day__c,DD_Collection_Period__c,DD_Collection_Stretch__c,DD_Start_Date__c FROM Income_Direct_Debit__c Where ID IN: newRecordIds];
        //{"StartDate":"2021-12-06","NumberOfDaysToWaitFromNewInstruction":"5","CollectionPeriod":"Monthly","CollectionDay":"1"}
        String endpointURL = '';
    for(Integer i=0;i<100 && i<newRecords.size();i++){
        SMP_DDServiceNextCollectionModel parsedResponse = new SMP_DDServiceNextCollectionModel();
        try{
            endpointURL = string.valueOf(directDebitConfig.Calculate_Next_Collection_Date_Endpoint__c);
            
        }catch(Exception e){
            System.debug('#### Couldn\'t find setup records!');
            System.debug('#### Exception: ' + e);
        }
        try{
                JSONGenerator gen = JSON.createGenerator(true);
                gen.writeStartObject();
                gen.writeStringField('StartDate', newRecords[i].DD_Start_Date__c.year()+'-'+newRecords[i].DD_Start_Date__c.month()+'-'+newRecords[i].DD_Start_Date__c.day());
                gen.writeStringField('NumberOfDaysToWaitFromNewInstruction', WAIT_PEROID_NEW_INSTRUCTION);
                gen.writeStringField('CollectionPeriod', newRecords[i].DD_Collection_Period__c);
                gen.writeStringField('CollectionDay', newRecords[i].DD_Collection_Day__c);
                gen.writeEndObject();
                gen.close();
                endpointURL = endpointURL + EncodingUtil.urlEncode(gen.getAsString(), 'UTF-8');
               
                HttpRequest req = new HttpRequest();
                Http http = new Http();
                req.setMethod('GET'); 
                req.setEndPoint(endpointURL);      
                HttpResponse resp;
                resp = http.send(req);
                if(resp.getStatusCode() == 200)
                {
                    parsedResponse = SMP_DDServiceNextCollectionModel.parse(resp.getBody());
                  
                    newRecords[i].DD_First_Collection_Date__c = Date.valueof(parsedResponse.ProcessNewDDFirstCollectionDateResult.FirstCollectionDate);
                    newRecords[i].DD_Next_Collection_Date__c = Date.valueof(parsedResponse.ProcessNewDDFirstCollectionDateResult.FirstCollectionDate);
            }
                else
                {
                    newRecords[i].Failed_Reason__c=MESSAGE_CALLOUTERROR + ' ' + resp.getStatusCode() + ' ' + resp.getStatus();
                    newRecords[i].DD_Status__c ='Failed';
                    parsedResponse.ProcessNewDDFirstCollectionDateResult.Error = MESSAGE_CALLOUTERROR + ' ' + resp.getStatusCode() + ' ' + resp.getStatus();
                }

                
                
        }
        catch(Exception e)
        {
            newRecords[i].DD_Status__c ='Failed';
            system.debug('Exception Occurred===>'+e);
            system.debug('parsedResponse Occurred===>'+parsedResponse);

        }
        if(newRecords.size()>0)
        update newRecords;
    }
}
   
}