force-app/main/default/objects/Recurring_Donation_Batch_Errors__c/Recurring_Donation_Batch_Errors__c.object-meta.xml
<CustomObject>
    <description>Error Logs</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>RD-{DD}-{MM}-{0000}</displayFormat>
        <label>ERROR #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recurring_Donation_Batch_Errors__c/fields/basketId__c.field-meta.xml
<CustomField>
    <fullName>basketId__c</fullName>
    <label>basketId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recurring_Donation_Batch_Errors__c/fields/Error_Context__c.field-meta.xml
<CustomField>
    <fullName>Error_Context__c</fullName>
    <label>Error Context</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Recurring_Donation_Batch_Errors__c/fields/EventDetails__c.field-meta.xml
<CustomField>
    <fullName>EventDetails__c</fullName>
    <label>Request Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/HA_Logger.cls
/**
 * @description       : 
 * @author            : Iamsfdeveloper
 * @group             : 
 * @last modified on  : 01-16-2022
 * @last modified by  : Iamsfdeveloper
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   02-08-2021   Iamsfdeveloper   Initial Version
**/
public with sharing class HA_Logger {

    public static Recurring_Donation_Batch_Errors__c CreateErrorLog(String requestDetails,String basketId,String ErrorContext){
        Recurring_Donation_Batch_Errors__c error=  new Recurring_Donation_Batch_Errors__c(basketId__c = basketId,EventDetails__c =requestDetails,Error_Context__c=ErrorContext);
       return error;
    }
}