force-app/main/default/objects/Opportunity/fields/Donation__c.field-meta.xml
<CustomField>
    <fullName>Donation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Donation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Donation</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>Paid</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Refunds</relationshipLabel>
    <relationshipName>SourceDonations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sponsorship__c/Sponsorship__c.object-meta.xml
<CustomObject>
    <label>Sponsorship</label>
    <nameField>
        <label>Sponsorship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sponsorships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sponsorship__c/fields/Donation__c.field-meta.xml
<CustomField>
    <fullName>Donation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Donation</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sponsorship__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Donor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Donor</value>
        </filterItems>
        <filterItems>
            <field>Contact.Is_Donor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sponsorship__c/fields/Donor_Organization__c.field-meta.xml
<CustomField>
    <fullName>Donor_Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Donor (Organization)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sponsorship__c/fields/Orphan__c.field-meta.xml
<CustomField>
    <fullName>Orphan__c</fullName>
    <label>Orphan</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <errorMessage>Please select different Orphan</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Orphan</value>
        </filterItems>
        <filterItems>
            <field>Contact.Active_Sponsorships__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filterItems>
        <infoMessage>Select Orphan Contacts with no Sponsorships</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orphan Sponsorships</relationshipLabel>
    <relationshipName>Sponsoree</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sponsorship__c/fields/Recurring_Donation__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Donation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recurring Donation</label>
    <referenceTo>npe03__Recurring_Donation__c</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sponsorship__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Orphan_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Orphan_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sponsored By HA</fullName>
    </customValue>
    <customValue>
        <fullName>Sponsored</fullName>
        <label>Sponsored by Donor</label>
    </customValue>
    <customValue>
        <fullName>Unsponsored</fullName>
        <default>true</default>
        <label>Unsponsored</label>
    </customValue>
    <masterLabel>Orphan Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HA_DonationPaymentFailed.cls
/**
 * @description       : Check if the latest three payment have failed and inactivated the sponsorship
 * @author            : Kalpesh.Thakur@HumanAppeal.co.uk
 * @group             : 
 * @last modified on  : 10-12-2021
 * @last modified by  : Kalpesh.Thakur@HumanAppeal.co.uk
 * Modifications Log 
 * Ver   Date         Author                             Modification
 * 1.0   10-12-2021   Kalpesh.Thakur@HumanAppeal.co.uk   Initial Version
**/
global class HA_DonationPaymentFailed extends npsp.TDTM_Runnable  {
	
    global override npsp.TDTM_Runnable.DmlWrapper run(List<SObject> newlist,
                                             List<SObject> oldlist,
                                             npsp.TDTM_Runnable.Action triggerAction,
                                             Schema.DescribeSObjectResult objResult) {

        npsp.TDTM_Runnable.dmlWrapper dmlWrapper = new npsp.TDTM_Runnable.DmlWrapper();
        List<Opportunity> newOppList = (List<Opportunity>) newlist;
        List<Opportunity> oldOppList = (List<Opportunity>) oldlist;
        Map<Id,Opportunity> oldOppMap = new Map<Id,Opportunity>(oldOppList);

        if (triggerAction == npsp.TDTM_Runnable.Action.AfterUpdate) {
			
            Set<Id> recurringDonationIds = new Set<Id>(); 
            
            for (Opportunity objOpp : newOppList) {
                
                if (objOpp.StageName == 'Payment Failed' && objOpp.StageName != oldOppMap.get(objOpp.Id).StageName) {
                    	
                    recurringDonationIds.add(objOpp.npe03__Recurring_Donation__c);
                }
                
            }
            
            Map<Id,List<Opportunity>> mapDonationByRecurring = new Map<Id,List<Opportunity>>();
            Map<Id,Datetime> mapRecurringByStartDate = new Map<Id,Datetime>();

            
            for (npe03__Recurring_Donation__c objRecurringDonation : [SELECT Id, Name ,
                                                                     (SELECT Id,Name,StageName,npe03__Recurring_Donation__c,CreatedDate FROM npe03__Donations__r ORDER BY CreatedDate DESC LIMIT 3)  
                                                                      FROM npe03__Recurring_Donation__c 
                                                                      WHERE Id=:recurringDonationIds]) {
				
                if (objRecurringDonation.npe03__Donations__r.size() == 3) {
                  
                    for (Opportunity objDonation : objRecurringDonation.npe03__Donations__r) {
                    
                        if (mapDonationByRecurring.containsKey(objDonation.npe03__Recurring_Donation__c)
                        && objDonation.StageName == 'Payment Failed') {
                        
                            mapDonationByRecurring.get(objDonation.npe03__Recurring_Donation__c).add(objDonation);
                            
                            if (mapRecurringByStartDate.get(objDonation.npe03__Recurring_Donation__c) > objDonation.CreatedDate) {
                             	
                                mapRecurringByStartDate.put(objDonation.npe03__Recurring_Donation__c,objDonation.CreatedDate);
                            }
                        }
                        else if (objDonation.StageName == 'Payment Failed') {
                            
                            mapDonationByRecurring.put(objDonation.npe03__Recurring_Donation__c, new List<Opportunity>{objDonation});
                            mapRecurringByStartDate.put(objDonation.npe03__Recurring_Donation__c,objDonation.CreatedDate);
                        }
                	}
                }
            }
            
            Set<Id> failedRecurringDonationIds = new Set<Id>();
            
            for (Id recurringDonationId : mapDonationByRecurring.keyset()) {
                
                if (mapDonationByRecurring.get(recurringDonationId).size() == 3) {
                    	
                    failedRecurringDonationIds.add(recurringDonationId);
                } 
            }
            
            List<Sponsorship__c> lstSponsorship = new List<Sponsorship__c>();
            
            for (npe03__Recurring_Donation__c objRecurringDonation : [SELECT Id, Name ,
                                                                     (SELECT Id,Name,Recurring_Donation__c,IsActive__c,Donor_Organization__c,Donor__c,Donation__c, 
                                                                      		End_Date_Time__c,Orphan__c,Start_Date_Time__c,Status__c  
                                                                      FROM Sponsorships__r WHERE IsActive__c=true)  
                                                                      FROM npe03__Recurring_Donation__c 
                                                                      WHERE Id=:failedRecurringDonationIds]) {
                
                for (Sponsorship__c objSponsorship : objRecurringDonation.Sponsorships__r) {
                                                    
                    objSponsorship.End_Date_Time__c = Date.today();
                    objSponsorship.IsActive__c = false;
                    lstSponsorship.add(objSponsorship);
                    
                    Sponsorship__c objHASponsorship = objSponsorship.Clone(false, false, false, false);
                    objHASponsorship.Start_Date_Time__c = mapRecurringByStartDate.get(objRecurringDonation.Id);
                    objHASponsorship.Donor_Organization__c = Label.Donor_Organization_Id;
                    objHASponsorship.Donor__c = '';
                    objHASponsorship.End_Date_Time__c = null;
                    objHASponsorship.IsActive__c = true;
					objHASponsorship.Status__c = 'Sponsored By HA'; 
                    lstSponsorship.add(objHASponsorship);
                    
                }                                           
            }
            upsert lstSponsorship;
        }
      
      return dmlWrapper;
    }
}