force-app/main/default/objects/Contact/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Specifies if contact is active, it is defaulted to active is true/checked.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sponsoree_Reserved_Until__c.field-meta.xml
<CustomField>
    <fullName>Sponsoree_Reserved_Until__c</fullName>
    <description>To be used with the reserved button to specify the date the reservation expires.</description>
    <label>Reserved Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sponsorship_Status__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Status__c</fullName>
    <label>Sponsorship Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sponsored</fullName>
                <label>Sponsored By Donor</label>
            </value>
            <value>
                <fullName>Unsponsored</fullName>
                <default>true</default>
                <label>Unsponsored</label>
            </value>
            <value>
                <fullName>Sponsored By HA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Orphan.recordType-meta.xml
<RecordType>
    <fullName>Orphan</fullName>
    <active>true</active>
    <description>Orphan</description>
    <label>Orphan</label>
</RecordType>

force-app/main/default/classes/HA_UnReservedBatch_Test.cls
@isTest
public with sharing class HA_UnReservedBatch_Test {
    
    public static Date reservedDate = Date.newInstance(2022, 01, 20);
    @TestSetup
    static void makeData() {
        Callable npspApi = (System.Callable)Type.forName('npsp', 'Callable_API').newInstance();
        Boolean isNpspTriggerDisabled = (Boolean)npspApi.call('TDTM.DisableAllTriggers', new Map<String, Object>());
        
         List<Contact> orphanContacts = (List<Contact>) TestFactory.createSObjectList(
            new Contact(RecordTypeId=Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Orphan').getRecordTypeId(),Is_Active__c=true,Sponsorship_Status__c='Unsponsored',Sponsoree_Reserved_Until__c=reservedDate),
            1,
            true
        );
    }
    
    @isTest
    Static void unit_1(){
        Test.startTest(); 
            HA_UnReservedBatch myBatch = new HA_UnReservedBatch();
            Database.executeBatch(myBatch,1);
        Test.stopTest();
    
    }

}