force-app/main/default/objects/Contact/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Specifies if contact is active, it is defaulted to active is true/checked.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sponsoree_Is_Reserved__c.field-meta.xml
<CustomField>
    <fullName>Sponsoree_Is_Reserved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Meant to allow a sponsoree to be reserved for a potential future sponsorship.</description>
    <label>Reserved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sponsoree_Reserved_Until__c.field-meta.xml
<CustomField>
    <fullName>Sponsoree_Reserved_Until__c</fullName>
    <description>To be used with the reserved button to specify the date the reservation expires.</description>
    <label>Reserved Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sponsorship_Status__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Status__c</fullName>
    <label>Sponsorship Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sponsored</fullName>
                <label>Sponsored By Donor</label>
            </value>
            <value>
                <fullName>Unsponsored</fullName>
                <default>true</default>
                <label>Unsponsored</label>
            </value>
            <value>
                <fullName>Sponsored By HA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Orphan.recordType-meta.xml
<RecordType>
    <fullName>Orphan</fullName>
    <active>true</active>
    <description>Orphan</description>
    <label>Orphan</label>
</RecordType>

force-app/main/default/classes/HA_UnReservedBatch.cls
public class HA_UnReservedBatch implements Database.Batchable<sObject> {

    public Database.QueryLocator start(Database.BatchableContext BC){
        
      //String query = 'SELECT Id,Name,Sponsoree_Is_Reserved__c,Sponsoree_Reserved_Until__c  FROM Contact WHERE Sponsoree_Reserved_Until__c <= LAST_MONTH AND Sponsorship_Status__c !=\'Sponsored \'';  
      String query ='SELECT Id,Name,Sponsoree_Is_Reserved__c,Sponsoree_Reserved_Until__c FROM Contact WHERE Sponsoree_Reserved_Until__c <= LAST_MONTH AND Sponsorship_Status__c !=\'Sponsored\' AND Is_Active__c = true AND RecordType.Name = \'Orphan\'';
      return Database.getQueryLocator(query);
   }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope) {

   		List<Contact> lstContacts = (List<Contact>) scope; 
        
        for (Contact objContact : lstContacts) {
            
            objContact.Sponsoree_Is_Reserved__c = false;
            objContact.Sponsoree_Reserved_Until__c = null;
        }
        
        update lstContacts;
 
    }
    
   	public void finish(Database.BatchableContext BC) {
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        mail.setToAddresses(new String[] {UserInfo.getUserEmail()});
        mail.setSenderDisplayName('Human Appeal');
        mail.setSubject('Batch Processing Reserved Orphans');
        mail.setPlainTextBody('Batch Process has completed');
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });       
       
   	
    }
}