force-app/main/default/objects/Contact/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Specifies if contact is active, it is defaulted to active is true/checked.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sponsorship__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsorship</label>
    <referenceTo>Sponsorship__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sponsorship_Status__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Status__c</fullName>
    <label>Sponsorship Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sponsored</fullName>
                <label>Sponsored By Donor</label>
            </value>
            <value>
                <fullName>Unsponsored</fullName>
                <default>true</default>
                <label>Unsponsored</label>
            </value>
            <value>
                <fullName>Sponsored By HA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sponsorship__c/Sponsorship__c.object-meta.xml
<CustomObject>
    <label>Sponsorship</label>
    <nameField>
        <label>Sponsorship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sponsorships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sponsorship__c/fields/Acknowledgment_Status__c.field-meta.xml
<CustomField>
    <fullName>Acknowledgment_Status__c</fullName>
    <label>Acknowledgment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Email Acknowledgment Now</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sponsorship__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Donor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Donor</value>
        </filterItems>
        <filterItems>
            <field>Contact.Is_Donor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sponsorship__c/fields/Donor_Organization__c.field-meta.xml
<CustomField>
    <fullName>Donor_Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Donor (Organization)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sponsorship__c/fields/Orphan__c.field-meta.xml
<CustomField>
    <fullName>Orphan__c</fullName>
    <label>Orphan</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <errorMessage>Please select different Orphan</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Orphan</value>
        </filterItems>
        <filterItems>
            <field>Contact.Active_Sponsorships__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filterItems>
        <infoMessage>Select Orphan Contacts with no Sponsorships</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orphan Sponsorships</relationshipLabel>
    <relationshipName>Sponsoree</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sponsorship__c/fields/Recurring_Donation__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Donation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recurring Donation</label>
    <referenceTo>npe03__Recurring_Donation__c</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sponsorship__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Orphan_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Orphan_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sponsored By HA</fullName>
    </customValue>
    <customValue>
        <fullName>Sponsored</fullName>
        <label>Sponsored by Donor</label>
    </customValue>
    <customValue>
        <fullName>Unsponsored</fullName>
        <default>true</default>
        <label>Unsponsored</label>
    </customValue>
    <masterLabel>Orphan Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ManageSponsorshipAfterEndDate.cls
public class ManageSponsorshipAfterEndDate implements Database.Batchable<sObject>{
   public final String Query = 'SELECT Id, Name, Orphan__c,Orphan__r.Is_Active__c, Donor__c, End_Date_Time__c, IsActive__c, Recurring_Donation__c, Status__c, Acknowledgment_Status__c FROM Sponsorship__c WHERE End_Date_Time__c = YESTERDAY AND IsActive__c = true';

   public Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   }

   public void execute(Database.BatchableContext BC, List<sObject> scope){
      
       List<Sponsorship__c> lstSponsorship = (List<Sponsorship__c>) scope;  
       
       List<Sponsorship__c> lstNewHASponsorship = new List<Sponsorship__c>();
       
       List<Contact> lstUpdateOrphan = new List<Contact>();
       
       for (Sponsorship__c objSponsor : lstSponsorship) {
           	
           objSponsor.IsActive__c = false;
           if(objSponsor.Orphan__r.Is_Active__c){
               Sponsorship__c objHASponsor = new Sponsorship__c();
               objHASponsor.Donor_Organization__c = Label.Donor_Organization_Id ;
               objHASponsor.IsActive__c = true;
               objHASponsor.Orphan__c = objSponsor.Orphan__c;
               objHASponsor.Start_Date_Time__c = Datetime.now();
               objHASponsor.Status__c = 'Sponsored By HA';
               lstNewHASponsorship.add(objHASponsor);
           }
 
       }
       
      
       
       insert lstNewHASponsorship;
       
       for (Sponsorship__c objHASponsor : lstNewHASponsorship) {
           	           
           Contact objOrphan = new Contact();
           objOrphan.Id = objHASponsor.Orphan__c;
           objOrphan.Sponsorship_Status__c  = 'Sponsored By HA';
           objOrphan.Sponsorship__c = objHASponsor.Id;
           lstUpdateOrphan.add(objOrphan);
       }
       
       
       update lstUpdateOrphan;   
       
       update lstSponsorship;
   }

   public void finish(Database.BatchableContext BC){
		
       Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        mail.setToAddresses(new String[] {UserInfo.getUserEmail()});
        mail.setSenderDisplayName('Human Appeal');
        mail.setSubject('Batch Processing Sponosorship After EndDate');
        mail.setPlainTextBody('Batch Process has completed');
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });       
       
   }

}