force-app/main/default/objects/Contact/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <description>Indicates if this Contact is designated as the Primary Contact on their Account (read only).</description>
    <formula>Account.npe01__One2OneContact__c = Id</formula>
    <inlineHelpText>This is is checked if the user is the Primary Contact on their Account.  The Primary Contact can be edited on the Account.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HA_Payment_Schedule__c/HA_Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Payment Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Income_Debit_History__c/Income_Debit_History__c.object-meta.xml
<CustomObject>
    <label>Income Debit History</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Income Debit History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Debit History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Income_Debit_History__c/fields/DD_Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>DD_Collection_Date__c</fullName>
    <label>DD Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Income_Debit_History__c/fields/DD_Stage__c.field-meta.xml
<CustomField>
    <fullName>DD_Stage__c</fullName>
    <label>DD Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
                <default>true</default>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Debit_History__c/fields/DD_Status__c.field-meta.xml
<CustomField>
    <fullName>DD_Status__c</fullName>
    <label>DD Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Debit_History__c/fields/Income_Direct_Debit__c.field-meta.xml
<CustomField>
    <fullName>Income_Direct_Debit__c</fullName>
    <label>Income Direct Debit</label>
    <referenceTo>Income_Direct_Debit__c</referenceTo>
    <relationshipLabel>Income Debit History</relationshipLabel>
    <relationshipName>Income_Debit_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Income_Debit_History__c/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Schedule</label>
    <referenceTo>Payment_Schedule__c</referenceTo>
    <relationshipLabel>Income Debit History</relationshipLabel>
    <relationshipName>Income_Debit_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/Income_Direct_Debit__c.object-meta.xml
<CustomObject>
    <label>Direct Debit Detail</label>
    <nameField>
        <displayFormat>DD{00000000}</displayFormat>
        <label>AUDDIS Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct Debit Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Income_Direct_Debit__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Income_Direct_Debit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Account_Number_OK__c.field-meta.xml
<CustomField>
    <fullName>DD_Account_Number_OK__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account Number OK</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>DD_Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Bank_Sort_Code__c.field-meta.xml
<CustomField>
    <fullName>DD_Bank_Sort_Code__c</fullName>
    <label>Bank Sort Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Collection_Day__c.field-meta.xml
<CustomField>
    <fullName>DD_Collection_Day__c</fullName>
    <label>Collection Day</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DD_Collection_Period__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Collection_Period__c.field-meta.xml
<CustomField>
    <fullName>DD_Collection_Period__c</fullName>
    <label>Collection Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_OK__c.field-meta.xml
<CustomField>
    <fullName>DD_OK__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DD OK</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Sort_Code_OK__c.field-meta.xml
<CustomField>
    <fullName>DD_Sort_Code_OK__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sort Code OK</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>DD_Start_Date__c</fullName>
    <inlineHelpText>DDs will not be collected before this date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/DD_Status__c.field-meta.xml
<CustomField>
    <fullName>DD_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Instruction</fullName>
                <default>true</default>
                <label>New Instruction</label>
            </value>
            <value>
                <fullName>First Collection</fullName>
            </value>
            <value>
                <fullName>Ongoing Collection</fullName>
            </value>
            <value>
                <fullName>Final Collection</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>First Represent</fullName>
            </value>
            <value>
                <fullName>Second Represent</fullName>
            </value>
            <value>
                <fullName>Third Represent</fullName>
            </value>
            <value>
                <fullName>Cancelled by Payer</fullName>
            </value>
            <value>
                <fullName>Cancelled by Originator</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Direct_Debit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Income_Direct_Debit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <description>Donation Type</description>
    <label>Donation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donation_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Contact for this Opportunity. If this is an individual Donation, NPSP attributes the Donation to the Primary Contact. If this is an organizational Donation, NPSP attributes a soft credit to the Primary Contact.</description>
    <inlineHelpText>The primary contact for this opportunity. The primary contact role is kept in sync with this field. For individual donations, this denotes attribution for this opportunity.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Schedule</label>
    <referenceTo>HA_Payment_Schedule__c</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Deprecated Payment Schedule</label>
    <nameField>
        <displayFormat>PSN-{0}</displayFormat>
        <label>Payment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deprecated Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Schedule__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Payment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outstanding</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Schedule_Allocation__c/Payment_Schedule_Allocation__c.object-meta.xml
<CustomObject>
    <label>Payment Schedule Allocation</label>
    <nameField>
        <displayFormat>PSA-{0000}</displayFormat>
        <label>Payment Schedule Allocation#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedule Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Schedule_Allocation__c/fields/General_Accounting_Unit__c.field-meta.xml
<CustomField>
    <fullName>General_Accounting_Unit__c</fullName>
    <label>Item Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>npsp__General_Accounting_Unit__c.npsp__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>npsp__General_Accounting_Unit__c</referenceTo>
    <relationshipLabel>Payment Schedule Allocations</relationshipLabel>
    <relationshipName>Payment_Schedule_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule_Allocation__c/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <label>Payment Schedule</label>
    <referenceTo>HA_Payment_Schedule__c</referenceTo>
    <relationshipLabel>Payment Schedule Allocations</relationshipLabel>
    <relationshipName>Payment_Schedule_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TriggerSettings__c/fields/Direct_Debit_History_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Direct_Debit_History_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Direct Debit History Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSettings__c/fields/Payment_Schedule_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Payment Schedule Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Donation_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SD</fullName>
        <label>Single</label>
    </customValue>
    <customValue>
        <fullName>RD</fullName>
        <label>Recurring Monthly</label>
    </customValue>
    <customValue>
        <fullName>10N</fullName>
        <label>10 Nights</label>
    </customValue>
    <customValue>
        <fullName>RDA</fullName>
        <label>Recurring Annually</label>
    </customValue>
    <customValue>
        <fullName>WK</fullName>
        <label>Weekly</label>
    </customValue>
    <customValue>
        <fullName>30N</fullName>
        <label>30 Nights</label>
    </customValue>
    <customValue>
        <fullName>27N</fullName>
        <label>27 Night</label>
    </customValue>
    <customValue>
        <fullName>30D</fullName>
        <label>30 Days</label>
    </customValue>
    <customValue>
        <fullName>EMI</fullName>
    </customValue>
    <customValue>
        <fullName>10D</fullName>
    </customValue>
    <description>Donation Types</description>
    <masterLabel>Donation Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TriggerHandler_DirectDebitHistoryTest.cls
@isTest
public with sharing class TriggerHandler_DirectDebitHistoryTest
{
    @testSetup
    static void createData(){
        
        List<HA_Payment_Schedule__c> paymentScheduleList = (List<HA_Payment_Schedule__c>)TestFactory.createSObjectList(new HA_Payment_Schedule__c(),2,'TestFactoryDefaults.PaymentSchedulesDefaults');
        insert paymentScheduleList;
        System.debug(JSON.serialize(paymentScheduleList[0]));
        List<npsp__General_Accounting_Unit__c> items = (List<npsp__General_Accounting_Unit__c>)TestFactory.createSObjectList(new npsp__General_Accounting_Unit__c(),1,'TestFactoryDefaults.GeneralAccountUnitsDefaults');
        insert items;
        Payment_Schedule_Allocation__c PSA1 = new Payment_Schedule_Allocation__c(General_Accounting_Unit__c= items[0].Id,Payment_Schedule__c = paymentScheduleList[0].Id);
        insert PSA1;
        Payment_Schedule_Allocation__c  PSA2 = new Payment_Schedule_Allocation__c(General_Accounting_Unit__c= items[0].Id,Payment_Schedule__c = paymentScheduleList[1].Id);
        insert PSA2;
        List<Contact> contactList = (List<Contact>) TestFactory.createSObjectList(
            new Contact(),
            1,
            true
        );
        TriggerSettings__c triggersettings = new TriggerSettings__c();
        triggersettings.Direct_Debit_History_Trigger__c = true;
        triggersettings.Payment_Schedule_Trigger__c = false;
        insert triggersettings;
        
        
        
    }
    
    
    @isTest static void testPaymentScheduleConnected() {
        List<npsp__Trigger_Handler__c> listHandlers = npsp.TDTM_Config_API.getCachedRecords();
        npsp__Trigger_Handler__c th = new npsp__Trigger_Handler__c();
        th.Name = 'CreateRecurringService_TDTM';
        th.npsp__Class__c = 'CreateRecurringService_TDTM';
        th.npsp__Object__c = 'Opportunity';
        th.npsp__Trigger_Action__c = 'AfterInsert,AfterUpdate';
        th.npsp__Active__c = true;
        th.npsp__Load_Order__c = 5;
        th.npsp__Asynchronous__c = false;
        listHandlers.add(th);
        Contact member = [Select Id From Contact Where Email like '%@humanappeal.org.uk.test' limit 1];
         List<npsp__General_Accounting_Unit__c> items = [Select Id,Name  FROM npsp__General_Accounting_Unit__c Where Name like 'Test Item%'];
        Opportunity opp = new Opportunity();
        opp.Name = 'testOpp';
		opp.npsp__Primary_Contact__c = member.Id;
        opp.Amount = 5;
        opp.StageName = 'Awaiting Payment Details';
        opp.CloseDate = Date.Today();
        opp.Donation_Type__c ='RD';
        opp.Type= 'Payment Plan - Source';
        insert opp;
        npsp__Allocation__c itemAllocation1 = (npsp__Allocation__c)TestFactory.createSObject(new npsp__Allocation__c(),'TestFactoryDefaults.ItemAllocationDefaults',false);
        itemAllocation1.npsp__General_Accounting_Unit__c = items[0].Id;
        itemAllocation1.npsp__Amount__c=5;
        itemAllocation1.npsp__Opportunity__c = opp.Id;
        insert itemAllocation1;
        String responseBody = '{"ProcessNewDDFirstCollectionDateResult":{"FirstCollectionDate":"2022-02-18","Error":""}}';
        HttpRestCallOutMock fakeResponse = new HttpRestCallOutMock(200, responseBody);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        Test.startTest();
        Income_Direct_Debit__c directDebit = new Income_Direct_Debit__c(DD_Sort_Code_OK__c = true,DD_OK__c=true,DD_Account_Number_OK__c=true,DD_Collection_Day__c='1',DD_Collection_Period__c='Monthly',DD_Start_Date__c = System.today(),Opportunity__c = opp.Id, Contact__c = member.Id, DD_Status__c = 'New Instruction', DD_Bank_Account_Number__c = '00000000', DD_Bank_Sort_Code__c = '000000');
        insert directDebit;
        Payment_Schedule__c schedule = new Payment_Schedule__c(Opportunity__c = opp.Id, Status__c = 'Outstanding', Schedule_Date__c = Date.Today() + 5);
        insert schedule;
        
        Income_Debit_History__c directDebitHistory = new Income_Debit_History__c(Income_Direct_Debit__c = directDebit.Id, DD_Status__c = 'Ongoing Collection', DD_Collection_Date__c = Date.Today() + 5);
        insert directDebitHistory;
        Test.stopTest();
    }
    
    @isTest static void testPaymentScheduleSetToFailed() {
        
        
        Contact member = [Select Id From Contact Where Email like '%@humanappeal.org.uk.test' limit 1];
        
        Opportunity opp = new Opportunity();
        opp.npsp__Primary_Contact__c = member.Id;
        opp.Name = 'testOpp';
        opp.Amount = 5;
        opp.StageName = 'test';
        opp.CloseDate = Date.Today();
        insert opp;
        
        Income_Direct_Debit__c directDebit = new Income_Direct_Debit__c(Opportunity__c = opp.Id, Contact__c = member.Id, DD_Status__c = 'Ongoing Collection', DD_Bank_Account_Number__c = '00000000', DD_Bank_Sort_Code__c = '000000');
        insert directDebit;
        
        Payment_Schedule__c schedule = new Payment_Schedule__c(Opportunity__c = opp.Id, Status__c = 'Outstanding', Schedule_Date__c = Date.Today() + 5);
        insert schedule;
        
        Income_Debit_History__c directDebitHistory = new Income_Debit_History__c(Payment_Schedule__c = schedule.Id, 
                                                                                 Income_Direct_Debit__c = directDebit.Id, 
                                                                                 DD_Status__c = 'Ongoing Collection', 
                                                                                 DD_Collection_Date__c = Date.Today() + 5);
        insert directDebitHistory;
        
        directDebitHistory.DD_Stage__c = 'Failed';
        update directDebitHistory;      
        
    }
    
    @isTest static void testPaymentScheduleSetToSuccess() {
        Contact member = [Select Id From Contact Where Email like '%@humanappeal.org.uk.test' limit 1];
        
        Opportunity opp = new Opportunity();
		opp.npsp__Primary_Contact__c = member.Id;
        opp.Name = 'testOpp';
        opp.Amount = 5;
        opp.StageName = 'test';
        opp.CloseDate = Date.Today();
        insert opp;
        
        Income_Direct_Debit__c directDebit = new Income_Direct_Debit__c(Opportunity__c = opp.Id, Contact__c = member.Id, DD_Status__c = 'Ongoing Collection', DD_Bank_Account_Number__c = '00000000', DD_Bank_Sort_Code__c = '000000');
        insert directDebit;
        
        Payment_Schedule__c schedule = new Payment_Schedule__c(Opportunity__c = opp.Id,Status__c = 'Outstanding', Schedule_Date__c = Date.Today() + 5);
        insert schedule;
        
        Income_Debit_History__c directDebitHistory = new Income_Debit_History__c(Payment_Schedule__c = schedule.Id, 
                                                                                 Income_Direct_Debit__c = directDebit.Id, 
                                                                                 DD_Status__c = 'Ongoing Collection', 
                                                                                 DD_Collection_Date__c = Date.Today() + 5);
        insert directDebitHistory;
        
        directDebitHistory.DD_Stage__c = 'Successful';
        update directDebitHistory;      
    }
}