force-app/main/default/objects/Contact/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <description>Indicates if this Contact is designated as the Primary Contact on their Account (read only).</description>
    <formula>Account.npe01__One2OneContact__c = Id</formula>
    <inlineHelpText>This is is checked if the user is the Primary Contact on their Account.  The Primary Contact can be edited on the Account.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HA_Payment_Schedule__c/HA_Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Payment Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Income_Card_Payment__c/Income_Card_Payment__c.object-meta.xml
<CustomObject>
    <description>Smarter Pay - Card Payment Detail</description>
    <label>Card Payment Detail</label>
    <nameField>
        <displayFormat>HUAPP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Income_Card_Payment__c/fields/Authorisation_Date__c.field-meta.xml
<CustomField>
    <fullName>Authorisation_Date__c</fullName>
    <inlineHelpText>Card Payment Created DateTime</inlineHelpText>
    <label>Authorisation DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Income_Card_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/First_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Amount__c</fullName>
    <label>First Payment Amount</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/First_Payment_Taken__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Taken__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First Payment Taken</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Gateway_Customer_Reference__c.field-meta.xml
<CustomField>
    <fullName>Gateway_Customer_Reference__c</fullName>
    <label>Gateway Customer Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Income_Card_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Order_ID__c.field-meta.xml
<CustomField>
    <fullName>Order_ID__c</fullName>
    <description>Payment Intent   If First Payment is collected
Setup Intent , If No Payment is collected</description>
    <inlineHelpText>Payment Intent /Setup Intent Id</inlineHelpText>
    <label>Setup/Payment Intent Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Payment_Method_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method_Id__c</fullName>
    <externalId>true</externalId>
    <label>Payment Method Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Payment_Method_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method_Type__c</fullName>
    <label>Payment Method Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>card</fullName>
            </value>
            <value>
                <fullName>sepa_debit</fullName>
            </value>
            <value>
                <fullName>oppwa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Payment_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Vendor__c</fullName>
    <label>Payment Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Globalpay</fullName>
            </value>
            <value>
                <fullName>SagePayPi</fullName>
            </value>
            <value>
                <fullName>Stripe</fullName>
                <default>true</default>
                <label>Stripe</label>
            </value>
            <value>
                <fullName>Oppwa</fullName>
            </value>
            <value>
                <fullName>SagePay</fullName>
                <isActive>false</isActive>
                <label>SagePay</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <label>Transaction ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Full Refund</fullName>
            </value>
            <value>
                <fullName>Partial Refund</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Deferred_Released</fullName>
                <label>Deferred Released</label>
            </value>
            <value>
                <fullName>Deferred_Aborted</fullName>
                <label>Deferred Aborted</label>
            </value>
            <value>
                <fullName>Authenticate</fullName>
            </value>
            <value>
                <fullName>Authorised</fullName>
            </value>
            <value>
                <fullName>Authorised &amp; First Collection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/recordTypes/Card_Payment.recordType-meta.xml
<RecordType>
    <fullName>Card_Payment</fullName>
    <active>true</active>
    <label>Card Payment</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <description>Donation Type</description>
    <label>Donation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donation_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/npsp__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>npsp__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Contact for this Opportunity. If this is an individual Donation, NPSP attributes the Donation to the Primary Contact. If this is an organizational Donation, NPSP attributes a soft credit to the Primary Contact.</description>
    <inlineHelpText>The primary contact for this opportunity. The primary contact role is kept in sync with this field. For individual donations, this denotes attribution for this opportunity.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Schedule</label>
    <referenceTo>HA_Payment_Schedule__c</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Website Transaction ID (GUID)</description>
    <externalId>true</externalId>
    <label>Transaction Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Deprecated Payment Schedule</label>
    <nameField>
        <displayFormat>PSN-{0}</displayFormat>
        <label>Payment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deprecated Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Schedule__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Payment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule_Allocation__c/Payment_Schedule_Allocation__c.object-meta.xml
<CustomObject>
    <label>Payment Schedule Allocation</label>
    <nameField>
        <displayFormat>PSA-{0000}</displayFormat>
        <label>Payment Schedule Allocation#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedule Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Schedule_Allocation__c/fields/General_Accounting_Unit__c.field-meta.xml
<CustomField>
    <fullName>General_Accounting_Unit__c</fullName>
    <label>Item Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>npsp__General_Accounting_Unit__c.npsp__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>npsp__General_Accounting_Unit__c</referenceTo>
    <relationshipLabel>Payment Schedule Allocations</relationshipLabel>
    <relationshipName>Payment_Schedule_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule_Allocation__c/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <label>Payment Schedule</label>
    <referenceTo>HA_Payment_Schedule__c</referenceTo>
    <relationshipLabel>Payment Schedule Allocations</relationshipLabel>
    <relationshipName>Payment_Schedule_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Donation_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SD</fullName>
        <label>Single</label>
    </customValue>
    <customValue>
        <fullName>RD</fullName>
        <label>Recurring Monthly</label>
    </customValue>
    <customValue>
        <fullName>10N</fullName>
        <label>10 Nights</label>
    </customValue>
    <customValue>
        <fullName>RDA</fullName>
        <label>Recurring Annually</label>
    </customValue>
    <customValue>
        <fullName>WK</fullName>
        <label>Weekly</label>
    </customValue>
    <customValue>
        <fullName>30N</fullName>
        <label>30 Nights</label>
    </customValue>
    <customValue>
        <fullName>27N</fullName>
        <label>27 Night</label>
    </customValue>
    <customValue>
        <fullName>30D</fullName>
        <label>30 Days</label>
    </customValue>
    <customValue>
        <fullName>EMI</fullName>
    </customValue>
    <customValue>
        <fullName>10D</fullName>
    </customValue>
    <description>Donation Types</description>
    <masterLabel>Donation Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateRecurringService_TDTM_Test.cls
@isTest
public class CreateRecurringService_TDTM_Test {
    
    @testSetup
    static void createData(){
        
        List<HA_Payment_Schedule__c> paymentScheduleList = (List<HA_Payment_Schedule__c>)TestFactory.createSObjectList(new HA_Payment_Schedule__c(),2,'TestFactoryDefaults.PaymentSchedulesDefaults');
        insert paymentScheduleList;
        System.debug(JSON.serialize(paymentScheduleList[0]));
        List<npsp__General_Accounting_Unit__c> items = (List<npsp__General_Accounting_Unit__c>)TestFactory.createSObjectList(new npsp__General_Accounting_Unit__c(),1,'TestFactoryDefaults.GeneralAccountUnitsDefaults');
        insert items;
        Payment_Schedule_Allocation__c PSA1 = new Payment_Schedule_Allocation__c(General_Accounting_Unit__c= items[0].Id,Payment_Schedule__c = paymentScheduleList[0].Id);
        insert PSA1;
        Payment_Schedule_Allocation__c  PSA2 = new Payment_Schedule_Allocation__c(General_Accounting_Unit__c= items[0].Id,Payment_Schedule__c = paymentScheduleList[1].Id);
        insert PSA2;
        List<Contact> contactList = (List<Contact>) TestFactory.createSObjectList(
            new Contact(),
            1,
            true
        );
        
        
        
    } 
    @IsTest
    static void unit(){
        
        List<npsp__Trigger_Handler__c> listHandlers = npsp.TDTM_Config_API.getCachedRecords();
        
        npsp__Trigger_Handler__c th = new npsp__Trigger_Handler__c();
        th.Name = 'CreateRecurringService_TDTM';
        th.npsp__Class__c = 'CreateRecurringService_TDTM';
        th.npsp__Object__c = 'Opportunity';
        th.npsp__Trigger_Action__c = 'AfterInsert';
        th.npsp__Active__c = true;
        th.npsp__Load_Order__c = 5;
        th.npsp__Asynchronous__c = false;
        listHandlers.add(th);
        
        Test.startTest();
        
        List<npsp__General_Accounting_Unit__c> items = [Select Id,Name  FROM npsp__General_Accounting_Unit__c Where Name like 'Test Item%'];
        
        List<Campaign> campaignList=(List<Campaign>) TestFactory.createSObjectList(
            new Campaign(),
            2,
            true
        );
        /*Campaign Allocation Item*/
        npsp__Allocation__c itemAllocation1 = (npsp__Allocation__c)TestFactory.createSObject(new npsp__Allocation__c(),'TestFactoryDefaults.ItemAllocationDefaults',false);
        itemAllocation1.npsp__General_Accounting_Unit__c = items[0].Id;
        itemAllocation1.npsp__Campaign__c = campaignList[0].Id;
        itemAllocation1.npsp__percent__c=50;
        insert itemAllocation1;
        List<Contact> contactList = [Select Id,Name FROM Contact Where MailingPostalCode = 'SK8 2BL'];
        List<Opportunity> opplist=(List<Opportunity>) TestFactory.createSObjectList(
            new Opportunity(),
            2,
            false
        );
        
        for(Opportunity opp:opplist){
            opp.CampaignId = campaignList[0].Id;
            opp.Amount=100;
            opp.Donation_Type__c ='RD';
            opp.Type = 'Payment Plan - Source';
            opp.npsp__Primary_Contact__c = contactList[0].Id;
        }
        insert opplist;
        Income_Card_Payment__c cardPayment = new Income_Card_Payment__c(payment_Reference__c='InternalWizard',Gateway_Customer_Reference__c='cus_L9pBaWHpg3gMYk',First_Payment_Taken__c=true,First_Payment_Amount__c=100,order_ID__c='pi_3KrNcNGItx6TnYh40JKc0AFW',Payment_Method_Id__c='pm_1KrNf3GItx6TnYh4Yvowfb8G', Authorisation_Date__c =SYSTEM.now(),RecordTypeId=Schema.SObjectType.Income_Card_Payment__c.getRecordTypeInfosByDeveloperName().get('Card_Payment').getRecordTypeId(),payment_Vendor__c='Stripe',Payment_Method_Type__c ='card',Opportunity__c = opplist[0].Id, Contact__c = contactList[0].Id, Payment_Status__c = 'succeeded', Transaction_Type__c = 'Authorised');
        insert cardPayment;
        npe01__OppPayment__c paymentObject = new npe01__OppPayment__c();
        paymentObject.npe01__Opportunity__c =opplist[0].Id;
        paymentObject.RecordTypeId=Schema.SObjectType.npe01__OppPayment__c.getRecordTypeInfosByDeveloperName().get('Card_Payment').getRecordTypeId();
        paymentObject.npe01__Payment_Method__c = 'Card Payment';
        paymentObject.Payment_Status__c = 'succeeded';
        paymentObject.npe01__Payment_Date__c= System.Today();
        paymentObject.npsp__Gateway_Payment_ID__c ='pm_1KrNf3GItx6TnYh4Yvowfb8G';
        paymentObject.Order_ID__c ='pi_3KrNcNGItx6TnYh40JKc0AFW';
        paymentObject.Transaction_ID__c ='pi_3KrNcNGItx6TnYh40JKc0AFW';
        paymentObject.npe01__Payment_Amount__c = 0;
        paymentObject.npsp__Type__c='Setup';
        paymentObject.Transaction_Type__c ='Setup';
        paymentObject.Card_Details__c=cardPayment.Id;
        insert paymentObject;
        
        
        Test.stopTest();
        
    } 
    @IsTest
    static void unit_1(){
        
        List<npsp__Trigger_Handler__c> listHandlers = npsp.TDTM_Config_API.getCachedRecords();
        
        npsp__Trigger_Handler__c th = new npsp__Trigger_Handler__c();
        th.Name = 'CreateRecurringService_TDTM';
        th.npsp__Class__c = 'CreateRecurringService_TDTM';
        th.npsp__Object__c = 'Opportunity';
        th.npsp__Trigger_Action__c = 'AfterUpdate,BeforeUpdate';
        th.npsp__Active__c = true;
        th.npsp__Load_Order__c = 5;
        th.npsp__Asynchronous__c = false;
        listHandlers.add(th);
        
        Test.startTest();
        
        List<npsp__General_Accounting_Unit__c> items = [Select Id,Name  FROM npsp__General_Accounting_Unit__c Where Name like 'Test Item%'];
        
        List<Campaign> campaignList=(List<Campaign>) TestFactory.createSObjectList(
            new Campaign(),
            2,
            true
        );
        /*Campaign Allocation Item*/
        npsp__Allocation__c itemAllocation1 = (npsp__Allocation__c)TestFactory.createSObject(new npsp__Allocation__c(),'TestFactoryDefaults.ItemAllocationDefaults',false);
        itemAllocation1.npsp__General_Accounting_Unit__c = items[0].Id;
        itemAllocation1.npsp__Campaign__c = campaignList[0].Id;
        itemAllocation1.npsp__percent__c=50;
        insert itemAllocation1;
        List<Contact> contactList = [Select Id,Name FROM Contact Where MailingPostalCode = 'SK8 2BL'];
        List<Opportunity> opplist=(List<Opportunity>) TestFactory.createSObjectList(
            new Opportunity(),
            2,
            false
        );
        
        for(Opportunity opp:opplist){
            opp.CampaignId = campaignList[0].Id;
            opp.Amount=100;
            opp.Donation_Type__c ='RD';
            opp.Type = 'Payment Plan - Source';
            opp.npsp__Primary_Contact__c = contactList[0].Id;
        }
        insert opplist;
        Income_Card_Payment__c cardPayment = new Income_Card_Payment__c(payment_Reference__c='InternalWizard',Gateway_Customer_Reference__c='cus_L9pBaWHpg3gMYk',First_Payment_Taken__c=true,First_Payment_Amount__c=100,order_ID__c='pi_3KrNcNGItx6TnYh40JKc0AFW',Payment_Method_Id__c='pm_1KrNf3GItx6TnYh4Yvowfb8G', Authorisation_Date__c =SYSTEM.now(),RecordTypeId=Schema.SObjectType.Income_Card_Payment__c.getRecordTypeInfosByDeveloperName().get('Card_Payment').getRecordTypeId(),payment_Vendor__c='Stripe',Payment_Method_Type__c ='card',Opportunity__c = opplist[0].Id, Contact__c = contactList[0].Id, Payment_Status__c = 'succeeded', Transaction_Type__c = 'Authorised');
        insert cardPayment;
        npe01__OppPayment__c paymentObject = new npe01__OppPayment__c();
        paymentObject.npe01__Opportunity__c =opplist[0].Id;
        paymentObject.RecordTypeId=Schema.SObjectType.npe01__OppPayment__c.getRecordTypeInfosByDeveloperName().get('Card_Payment').getRecordTypeId();
        paymentObject.npe01__Payment_Method__c = 'Card Payment';
        paymentObject.Payment_Status__c = 'succeeded';
        paymentObject.npe01__Payment_Date__c= System.Today();
        paymentObject.npsp__Gateway_Payment_ID__c ='pm_1KrNf3GItx6TnYh4Yvowfb8G';
        paymentObject.Order_ID__c ='pi_3KrNcNGItx6TnYh40JKc0AFW';
        paymentObject.Transaction_ID__c ='pi_3KrNcNGItx6TnYh40JKc0AFW';
        paymentObject.npe01__Payment_Amount__c = 0;
        paymentObject.npsp__Type__c='Setup';
        paymentObject.Transaction_Type__c ='Setup';
        paymentObject.Card_Details__c=cardPayment.Id;
        insert paymentObject;
        
        
        Test.stopTest();
        
    } 
    
}