force-app/main/default/objects/Contact/fields/Regional_Office_Code__c.field-meta.xml
<CustomField>
    <fullName>Regional_Office_Code__c</fullName>
    <label>Regional_Office_Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regional_Office_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/Income_Card_Payment__c.object-meta.xml
<CustomObject>
    <description>Smarter Pay - Card Payment Detail</description>
    <label>Card Payment Detail</label>
    <nameField>
        <displayFormat>HUAPP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Income_Card_Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Income_Card_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Gateway_Customer_Reference__c.field-meta.xml
<CustomField>
    <fullName>Gateway_Customer_Reference__c</fullName>
    <label>Gateway Customer Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Income_Card_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Payment_Method_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method_Id__c</fullName>
    <externalId>true</externalId>
    <label>Payment Method Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Payment_Method_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method_Type__c</fullName>
    <label>Payment Method Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>card</fullName>
            </value>
            <value>
                <fullName>sepa_debit</fullName>
            </value>
            <value>
                <fullName>oppwa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Card_Payment__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Full Refund</fullName>
            </value>
            <value>
                <fullName>Partial Refund</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Deferred_Released</fullName>
                <label>Deferred Released</label>
            </value>
            <value>
                <fullName>Deferred_Aborted</fullName>
                <label>Deferred Aborted</label>
            </value>
            <value>
                <fullName>Authenticate</fullName>
            </value>
            <value>
                <fullName>Authorised</fullName>
            </value>
            <value>
                <fullName>Authorised &amp; First Collection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DonationCode__c.field-meta.xml
<CustomField>
    <fullName>DonationCode__c</fullName>
    <formula>Text(Payment_Schedule__r.Code__c)</formula>
    <label>Donation Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <description>Used for bulk upload process</description>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Regional_Office_Code__c.field-meta.xml
<CustomField>
    <fullName>Regional_Office_Code__c</fullName>
    <label>Regional_Office_Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regional_Office_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Regional_Office_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>US</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>Regional_Office_Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CardConfiguration.cls
public class CardConfiguration {
    @future(callout=true)
    public static void getCustomerPaymentMethod(set<Id> cardPaymentIds){
        
        if(cardPaymentIds.size()>0){
            Map<Id,Id> oppMapToCardPayment = new Map<Id,Id>();
            List<Opportunity> updateOpportunities = new List<Opportunity>();
            List<Income_Card_Payment__c> cardPaymentList = [Select Id,Transaction_Type__c,Payment_Status__c,Payment_Method_Id__c,Opportunity__c,Contact__r.Regional_Office_code__c,Gateway_Customer_Reference__c,Opportunity__r.Regional_office_code__c,Opportunity__r.DonationCode__c From Income_Card_Payment__c Where Id IN: cardPaymentIds and Payment_Method_Id__c = null];
            For(Income_Card_Payment__c cp:cardPaymentList){
                if (Limits.getCallouts() <= 100 && cp.Gateway_Customer_Reference__c != null &&  cp.Payment_Method_Id__c == null){
                    Opportunity opp = new Opportunity(Payment_Method__c ='Card Payment',Id=cp.Opportunity__c,StageName='In Payment Processing');
                    NewPaymentService ps = (NewPaymentService) di_Injector.Org.getInstance( NewPaymentService.class);
					HTTPResponse customerInfoResponse = ps.requestCustomerInformation(cp.Gateway_Customer_Reference__c,(cp.Opportunity__c != null)?cp.Opportunity__r.Regional_office_code__c:cp.Contact__r.Regional_Office_code__c);
                     if(customerInfoResponse.getStatusCode() ==200){
                            
                            Map<String,Object> responseMap =(Map<String,Object>)JSON.deserializeUntyped(customerInfoResponse.getBody());
                         Map<String,Object> invoiceSettingsMap =(Map<String,Object>)responseMap.get('invoice_settings');
                         if(String.valueOf(invoiceSettingsMap.get('default_payment_method')) != null ){
                             cp.Payment_Method_Id__c = String.valueOf(invoiceSettingsMap.get('default_payment_method'));
                             cp.Payment_Method_Type__c  = 'card';
                             if(cp.Opportunity__c != null && (cp.Transaction_Type__c =='Authenticate' || cp.Transaction_Type__c =='Sale'  || cp.Transaction_Type__c =='Authorised')  && (cp.Payment_Status__c =='succeeded' || cp.Payment_Status__c =='Successful')){
                                 
                                 Opp.StageName = 'Paid';
                                 if(cp.Opportunity__r.DonationCode__c =='10N' || cp.Opportunity__r.DonationCode__c =='30N' || cp.Opportunity__r.DonationCode__c == '10D'){
                                     Opp.StageName = 'Setup Completed';
                                     oppMapToCardPayment.put(cp.Opportunity__c,cp.Id);
                                 }
                                 updateOpportunities.add(opp);
                             
                             }
                         }
                     }
                    
                }
            }// End For loop
            
            Database.update(cardPaymentList,false);
            List<npe01__OppPayment__c> paymentsToUpdate = new List<npe01__OppPayment__c>();
            if(oppMapToCardPayment.size()>0){
                for(npe01__OppPayment__c payment : [Select Id,Card_Details__c,npe01__Opportunity__c,npe01__Paid__c FROM npe01__OppPayment__c Where npe01__Paid__c = false and npe01__Opportunity__c IN:oppMapToCardPayment.keySet() and (npe01__Opportunity__r.DonationCode__c ='30N' OR npe01__Opportunity__r.DonationCode__c ='10N' OR npe01__Opportunity__r.DonationCode__c ='10D')]){
                    payment.Card_Details__c = oppMapToCardPayment.get(payment.npe01__Opportunity__c);
                    paymentsToUpdate.add(payment);
                }
            }
            if(paymentsToUpdate.size()>0)
                Database.update(paymentsToUpdate,false);
            if(updateOpportunities.size()>0){
            	Database.update(updateOpportunities,false);
       		}
        }
    }// End of future Method
}