force-app/main/default/objects/Bulk_Upload_Data__c/Bulk_Upload_Data__c.object-meta.xml
<CustomObject>
    <label>Bulk Upload Data</label>
    <nameField>
        <displayFormat>BUDN-{0000}</displayFormat>
        <label>Bulk Upload Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Upload Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/agencyFees__c.field-meta.xml
<CustomField>
    <fullName>agencyFees__c</fullName>
    <label>agencyFees</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>amount</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/bank__c.field-meta.xml
<CustomField>
    <fullName>bank__c</fullName>
    <label>bank</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/bankReference__c.field-meta.xml
<CustomField>
    <fullName>bankReference__c</fullName>
    <label>bankReference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Bulk Upload Data</relationshipLabel>
    <relationshipName>Bulk_Upload_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/Campaign_Active__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Active__c</fullName>
    <label>Campaign Active</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/Campaign_Department__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Department__c</fullName>
    <label>Campaign Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/Campaign_Description__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Description__c</fullName>
    <label>Campaign Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/Campaign_Parent__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Parent__c</fullName>
    <label>Campaign Parent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/currCode__c.field-meta.xml
<CustomField>
    <fullName>currCode__c</fullName>
    <label>currCode</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/Donation_Date__c.field-meta.xml
<CustomField>
    <fullName>Donation_Date__c</fullName>
    <label>Donation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/donorId__c.field-meta.xml
<CustomField>
    <fullName>donorId__c</fullName>
    <label>donorId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <referenceTo>Bulk_Upload_Donations__c</referenceTo>
    <relationshipLabel>Bulk Upload Data</relationshipLabel>
    <relationshipName>Bulk_Upload_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/fundRaisingUrl__c.field-meta.xml
<CustomField>
    <fullName>fundRaisingUrl__c</fullName>
    <label>fundRaisingUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/gaEligible__c.field-meta.xml
<CustomField>
    <fullName>gaEligible__c</fullName>
    <label>gaEligible</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/GAU_Allocation__c.field-meta.xml
<CustomField>
    <fullName>GAU_Allocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GAU Allocation</label>
    <referenceTo>npsp__Allocation__c</referenceTo>
    <relationshipLabel>Bulk Upload Data</relationshipLabel>
    <relationshipName>Bulk_Upload_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/hasError__c.field-meta.xml
<CustomField>
    <fullName>hasError__c</fullName>
    <defaultValue>false</defaultValue>
    <label>hasError</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/Is_Campaign_Processed__c.field-meta.xml
<CustomField>
    <fullName>Is_Campaign_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Campaign Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/itemCode__c.field-meta.xml
<CustomField>
    <fullName>itemCode__c</fullName>
    <label>itemCode</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/medium__c.field-meta.xml
<CustomField>
    <fullName>medium__c</fullName>
    <label>medium</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/netDonationAmount__c.field-meta.xml
<CustomField>
    <fullName>netDonationAmount__c</fullName>
    <label>netDonationAmount</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bulk Upload Data</relationshipLabel>
    <relationshipName>Bulk_Upload_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>npe01__OppPayment__c</referenceTo>
    <relationshipLabel>Bulk Upload Data</relationshipLabel>
    <relationshipName>Bulk_Upload_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/paymentMethod__c.field-meta.xml
<CustomField>
    <fullName>paymentMethod__c</fullName>
    <label>paymentMethod</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/primaryCampaignSource__c.field-meta.xml
<CustomField>
    <fullName>primaryCampaignSource__c</fullName>
    <label>primaryCampaignSource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/regionalOffice__c.field-meta.xml
<CustomField>
    <fullName>regionalOffice__c</fullName>
    <label>regionalOffice</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/Row_Index__c.field-meta.xml
<CustomField>
    <fullName>Row_Index__c</fullName>
    <label>Row Index</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/sfAccountId__c.field-meta.xml
<CustomField>
    <fullName>sfAccountId__c</fullName>
    <label>sfAccountId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/sfContactId__c.field-meta.xml
<CustomField>
    <fullName>sfContactId__c</fullName>
    <label>sfContactId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/stage__c.field-meta.xml
<CustomField>
    <fullName>stage__c</fullName>
    <label>stage</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/stipulation__c.field-meta.xml
<CustomField>
    <fullName>stipulation__c</fullName>
    <label>stipulation</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <externalId>true</externalId>
    <label>Transaction Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Data__c/fields/transactionSource__c.field-meta.xml
<CustomField>
    <fullName>transactionSource__c</fullName>
    <label>transactionSource</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Donations__c/Bulk_Upload_Donations__c.object-meta.xml
<CustomObject>
    <label>Bulk Upload Donations</label>
    <nameField>
        <label>Bulk Upload Donations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bulk Upload Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bulk_Upload_Donations__c/fields/Error_Reason__c.field-meta.xml
<CustomField>
    <fullName>Error_Reason__c</fullName>
    <label>Error Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Bulk_Upload_Donations__c/fields/Upload_File_Type__c.field-meta.xml
<CustomField>
    <fullName>Upload_File_Type__c</fullName>
    <label>Upload File Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comms</fullName>
            </value>
            <value>
                <fullName>Donor Care</fullName>
            </value>
            <value>
                <fullName>Fundraising</fullName>
            </value>
            <value>
                <fullName>Emerging Market</fullName>
            </value>
            <value>
                <fullName>ME Fund Development</fullName>
            </value>
            <value>
                <fullName>Institutional Funding</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pledges</relationshipLabel>
    <relationshipName>Donor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Fundraising_page_url__c.field-meta.xml
<CustomField>
    <fullName>Fundraising_page_url__c</fullName>
    <label>Fundraising page url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>This can sometimes be known as &quot;Event Type&quot;</description>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Department__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Upload_Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Upload_Transaction_ID__c</fullName>
    <label>Upload Transaction ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Donor_Pledge.recordType-meta.xml
<RecordType>
    <fullName>Donor_Pledge</fullName>
    <active>true</active>
    <label>Donor Pledge</label>
</RecordType>

force-app/main/default/objects/Campaign/recordTypes/Pledge.recordType-meta.xml
<RecordType>
    <fullName>Pledge</fullName>
    <active>true</active>
    <description>Pledges for Fundraising pages</description>
    <label>Agency Pledge</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Donor_ID__c.field-meta.xml
<CustomField>
    <fullName>Donor_ID__c</fullName>
    <description>Unique Donor ID - Country Code + 7 Digits (UK1234567)</description>
    <externalId>true</externalId>
    <label>Donor ID</label>
    <length>9</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Donor.recordType-meta.xml
<RecordType>
    <fullName>Donor</fullName>
    <active>true</active>
    <description>Donor Contact</description>
    <label>Donor</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <inlineHelpText>Bank Name from Bulk Upload</inlineHelpText>
    <label>Bank</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>Department</description>
    <formula>IF((ISBLANK(npe03__Recurring_Donation__c)),TEXT( Campaign.Department__c),TEXT(npe03__Recurring_Donation__r.Opportunity__r.Campaign.Department__c))</formula>
    <inlineHelpText>Department</inlineHelpText>
    <label>Department</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Donor_ID__c.field-meta.xml
<CustomField>
    <fullName>Donor_ID__c</fullName>
    <formula>npsp__Primary_Contact__r.Donor_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Donor ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Fundraising_Page_URL__c.field-meta.xml
<CustomField>
    <fullName>Fundraising_Page_URL__c</fullName>
    <inlineHelpText>FundRaising page url from bulk upload</inlineHelpText>
    <label>Fundraising Page URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Medium__c.field-meta.xml
<CustomField>
    <fullName>Medium__c</fullName>
    <description>Describes the medium a donation is delivered to organisation for processing.</description>
    <label>Medium</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Medium</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Row_Index__c.field-meta.xml
<CustomField>
    <fullName>Row_Index__c</fullName>
    <description>Used for bulk upload</description>
    <label>Row Index</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Website Transaction ID (GUID)</description>
    <externalId>true</externalId>
    <label>Transaction Id</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Donation.recordType-meta.xml
<RecordType>
    <fullName>Donation</fullName>
    <active>true</active>
    <businessProcess>Donations</businessProcess>
    <description>Donations</description>
    <label>Donation</label>
</RecordType>

force-app/main/default/globalValueSets/Medium.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Post</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>In Person</fullName>
    </customValue>
    <customValue>
        <fullName>Bank Transfer</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Agency</fullName>
    </customValue>
    <masterLabel>Medium</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Affiliate / partner marketing (including sponsorship)</fullName>
    </customValue>
    <customValue>
        <fullName>Call Centre</fullName>
    </customValue>
    <customValue>
        <fullName>Challenge</fullName>
    </customValue>
    <customValue>
        <fullName>Collection – street, mosques</fullName>
    </customValue>
    <customValue>
        <fullName>Community Fundraising</fullName>
    </customValue>
    <customValue>
        <fullName>Display Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Email marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Events – Tours, Dinners, Challenges, Stalls</fullName>
    </customValue>
    <customValue>
        <fullName>High Network Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Influencer</fullName>
    </customValue>
    <customValue>
        <fullName>In Kind Donations</fullName>
    </customValue>
    <customValue>
        <fullName>Institutional Funds</fullName>
    </customValue>
    <customValue>
        <fullName>International Offices</fullName>
    </customValue>
    <customValue>
        <fullName>Leaflets / posters</fullName>
    </customValue>
    <customValue>
        <fullName>Organic search</fullName>
    </customValue>
    <customValue>
        <fullName>Paid search</fullName>
    </customValue>
    <customValue>
        <fullName>Partnerships</fullName>
    </customValue>
    <customValue>
        <fullName>Peer to Peer</fullName>
    </customValue>
    <customValue>
        <fullName>Pledges</fullName>
    </customValue>
    <customValue>
        <fullName>Post – direct mail, door drops</fullName>
    </customValue>
    <customValue>
        <fullName>PPC</fullName>
    </customValue>
    <customValue>
        <fullName>Radio Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Retail Shops</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Social media marketing – Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Social media marketing – Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Social media marketing –  Twitter</fullName>
    </customValue>
    <customValue>
        <fullName>Speaker</fullName>
    </customValue>
    <customValue>
        <fullName>Benevity</fullName>
        <label>Third party giving - Benevity</label>
    </customValue>
    <description>Used on Campaigns and Donations. Proposed configuration:  If Donation.Source is blank and Primary_Campaign_Source.Source is not blank,  then copy the Source from the Primary_Campaign_Source.Source to the Donation.Source</description>
    <masterLabel>Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BulkUploadProcessFutureCampaign.cls
/**
* @description       : 
* @author            : Iamsfdeveloper
* @group             : 
* @last modified on  : 06-30-2021
* @last modified by  : Iamsfdeveloper
* Modifications Log 
* Ver   Date         Author           Modification
* 1.0   06-07-2021   Iamsfdeveloper   Initial Version
**/
global class BulkUploadProcessFutureCampaign  implements Database.Batchable<sObject>, Database.Stateful{
    public  Set<String> donorIds = new Set<String>();
    public  Set<String> accountIds = new Set<String>();
    public  Set<String> contactIds = new Set<String>();
    public  static Map<String,ID> donorIdToContactIDMap = new Map<String,ID>();
    public  static Map<String,ID> campaignNameToIDMap = new Map<String,ID>();
    public  static Map<String,Bulk_Upload_Data__c> donorIdItemMap = new Map<String,Bulk_Upload_Data__c>();    
    public  Set<String> parentCampaign = new Set<String>();
    public  Static Id oppRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Donation').getRecordTypeId(); 
    public  Integer rowIndex = 0;
    public   List<Bulk_Upload_Data__c> dataInsertList = new List<Bulk_Upload_Data__c>();    
    public  String ErrorMessage;
    public  Id bulkRecordId;
    public  String upLoadType;
    public String dataFromSpreadsheet;
    public Boolean singleRun;
    public String query;
    public String recordTypeId;
    
    public BulkUploadProcessFutureCampaign(Id recId,String upType,String dataString,Boolean singleRunExecution) {
        this.bulkRecordId = recId;
        this.upLoadType = upType;
        dataFromSpreadsheet = dataString;
        singleRun = singleRunExecution; 
        if(upType == 'Pledge'){
            this.recordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('Pledge').getRecordTypeId();
        }else{
            this.recordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('Donor_Pledge').getRecordTypeId();
        }         
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('dataFromSpreadsheet=='+dataFromSpreadsheet);
        try{
            if(!String.isBlank(dataFromSpreadsheet) && singleRun == false){
                dataFromSpreadsheet = dataFromSpreadsheet.replace('Primary Campaign: Campaign Name', 'name');
                dataFromSpreadsheet = dataFromSpreadsheet.replace('Donor', 'donorId');
                dataFromSpreadsheet = dataFromSpreadsheet.replace('Description', 'description');
                dataFromSpreadsheet = dataFromSpreadsheet.replace('Fundraising page url', 'fundraisingURL');
                dataFromSpreadsheet = dataFromSpreadsheet.replace('Source', 'source');
                dataFromSpreadsheet = dataFromSpreadsheet.replace('Department', 'department');
                dataFromSpreadsheet = dataFromSpreadsheet.replace('Campaign Currency', 'currCode');
                dataFromSpreadsheet = dataFromSpreadsheet.replace('Active', 'isActive');
                dataFromSpreadsheet = dataFromSpreadsheet.replace('Status', 'status');
                dataFromSpreadsheet = dataFromSpreadsheet.replace('Holding Item code', 'donationItemCode');
                dataFromSpreadsheet = dataFromSpreadsheet.replace('Parent Campaign (Team Link)', 'parentCampaign');
                System.debug('dataFromSpreadsheet=='+dataFromSpreadsheet);
                List<CsvWrapper> dataList = (List<csvWrapper>)JSON.deserialize(dataFromSpreadsheet, List<CsvWrapper>.class);                 
                for(CsvWrapper c : dataList){ 
                    System.debug('c=='+c);
                    Bulk_Upload_Data__c tempList = new Bulk_Upload_Data__c ();
                    if(!String.isBlank(c.name)){
                        tempList.CampaignName__c  = c.name;
                        tempList.donorId__c = c.donorId;
                        tempList.Campaign_Description__c = c.description;
                        tempList.fundRaisingUrl__c = c.fundraisingURL;
                        tempList.Campaign_Department__c = c.department;                    
                        tempList.currCode__c = c.currCode;
                        tempList.Campaign_Active__c = c.isActive;
                        tempList.stage__c = c.status;
                        tempList.primaryCampaignSource__c = c.source;
                        tempList.itemCode__c = c.donationItemCode;
                        tempList.Campaign_Parent__c = c.parentCampaign;    
                        tempList.File_Name__c = bulkRecordId;
                        dataInsertList.add(tempList);
                    }
                    
                }
                Insert dataInsertList;            
                query = 'SELECT id,donorId__c,itemCode__c,File_Name__r.Upload_File_Type__c,CampaignName__c,'+
                    'stage__c,currCode__c,Campaign_Description__c,fundRaisingUrl__c,Campaign_Department__c,'+
                    'primaryCampaignSource__c,Campaign_Active__c, Campaign_Parent__c,'+
                    'File_Name__c,Row_Index__c FROM Bulk_Upload_Data__c WHERE File_Name__c='+'\''+bulkRecordId+'\'';
                
            }
        }Catch(Exception e){                
            ErrorMessage = e.getMessage();                
        }        
        system.debug('query'+query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Bulk_Upload_Data__c> scope) {
        
        Callable npspApi = (System.Callable)Type.forName('npsp', 'Callable_API').newInstance();
        Boolean isNpspTriggerDisabled = (Boolean)npspApi.call('TDTM.DisableAllTriggers', new Map<String, Object>());
        
        for(Bulk_Upload_Data__c c : scope){	
            if(!String.isBlank(c.donorId__c)){
                donorIds.add(c.donorId__c);               
            }
            if(!String.isBlank(c.Campaign_Parent__c)){
                parentCampaign.add(c.Campaign_Parent__c);
            }
        }
        
        for(Contact c : [Select Id, Donor_ID__c  FROM Contact where Donor_ID__c  IN: donorIds OR ID IN :donorIds]){
            donorIdToContactIDMap.put(c.Donor_ID__c,c.Id); 
        }
        
        for(Campaign c : [Select Id, Name FROM Campaign WHERE Name IN: parentCampaign]){
            campaignNameToIDMap.put(c.Name, c.Id); 
        }
        
        insertCampaign(scope, recordTypeId);
    }   
    
    global void finish(Database.BatchableContext BC) {
        if(String.isNotBlank(ErrorMessage))
            update new Bulk_Upload_Donations__c(Id=bulkRecordId,Error_Reason__c=ErrorMessage);
        else{
            BulkUploadBatch_GAU Allocationbatch = new BulkUploadBatch_GAU(bulkRecordId);
            Allocationbatch.executePaymentbatch = false;
            Allocationbatch.query = 'select id,Donation_Date__c,donorId__c,itemCode__c,stipulation__c,File_Name__r.Upload_File_Type__c,Campaign__c,'+
                'gaEligible__c,stage__c,currCode__c,amount__c,sfContactId__c,agencyFees__c,netDonationAmount__c,'+
                'bankReference__c,primaryCampaignSource__c,medium__c,paymentMethod__c,bank__c,'+
                'regionalOffice__c,fundRaisingUrl__c,sfAccountId__c,File_Name__c,Row_Index__c,Opportunity__c,Opportunity__r.Transaction_Id__c,GAU_Allocation__c,Payment__c,transactionSource__c  from Bulk_Upload_Data__c where GAU_Allocation__c = null and File_Name__c='+'\''+bulkRecordId+'\'';
            Database.executebatch(Allocationbatch,25);
        } 
    }
    
    
    private void insertCampaign(List<Bulk_Upload_Data__c> dataList, String recordTypeId){
        List<Campaign> newCampaign = new List<Campaign>();
        List<Bulk_Upload_Data__c> udpatedataList = new List<Bulk_Upload_Data__c>();
        Map<String,Campaign> campIdtoName = new Map<String,Campaign>();
        System.debug('campaignNameToIDMap=='+campaignNameToIDMap);
        for(Bulk_Upload_Data__c c : dataList){
            System.debug('c=='+c);
            if(c.Campaign_Parent__c != null && campaignNameToIDMap.containsKey(c.Campaign_Parent__c)){
                rowIndex+=1;
                Campaign cam = new Campaign();
                cam.ParentId = campaignNameToIDMap.get(c.Campaign_Parent__c);
                if(!String.isBlank(c.CampaignName__c)){
                    cam.Name = c.CampaignName__c;
                }                
                cam.Description = c.Campaign_Description__c;
                cam.Department__c = c.Campaign_Department__c;
                cam.IsActive = Boolean.valueOf(c.Campaign_Active__c);
                cam.Status = c.stage__c;
                cam.Source__c = c.primaryCampaignSource__c;
                cam.CurrencyIsoCode = c.currCode__c;
                cam.Upload_Transaction_ID__c = c.id;
                cam.RecordTypeId = recordTypeId;
                if(!String.isBlank(c.fundRaisingUrl__c)){
                    cam.Fundraising_page_url__c = c.fundRaisingUrl__c;
                }                
                if(c.donorId__c != null && !c.donorId__c.startsWith('003') && donorIdToContactIDMap.containsKey(c.donorId__c)){
                    cam.Donor__c = donorIdToContactIDMap.get(c.donorId__c);
                }else if(c.donorId__c != null && c.donorId__c.startsWith('003')){
                    cam.Donor__c = c.donorId__c;
                }
                newCampaign.add(cam);
                c.Row_Index__c = String.valueof(rowIndex);
                c.Error_Message__c = '';
                c.hasError__c = false;
            }else{
                c.Error_Message__c = 'Parent Campaign Not found';
                c.hasError__c = true;                
            }
        }
        System.debug('dataList=='+dataList);
        System.debug('newCampaign=='+newCampaign);
        update dataList;
        if(newCampaign.size() > 0){
            
            Database.SaveResult[] srList = Database.insert(newCampaign, false);
            System.debug('srList=='+srList);
            // Iterate through each returned result
            for (Integer i=0;i<srList.size();i++) {
                Database.SaveResult sr = srList[i];
                Campaign cam = newCampaign[i];
                Bulk_Upload_Data__c temp = new Bulk_Upload_Data__c(Id=cam.Upload_Transaction_ID__c);
                if (!sr.isSuccess()) {
                    String ErrorMessage = '';
                    for(Database.Error err : sr.getErrors()) {
                        ErrorMessage =err.getMessage();                         
                    }
                    temp.hasError__c = true;
                    temp.Error_Message__c = ErrorMessage;
                }else{
                    temp.hasError__c = false;
                    temp.Error_Message__c = '';
                    temp.Is_Campaign_Processed__c = true;
                    temp.Campaign__c = sr.getId();  
                }
                udpatedataList.add(temp);
            }
            if(udpatedataList.size()>0)
                Update udpatedataList;
        }
    }
    public class CsvWrapper{        
        public String name;
        public String donorId;
        public String description;
        public String fundraisingURL;
        public String source;
        public String currCode;
        public String department;
        public String isActive;
        public String status;
        public String donationItemCode;
        public String parentCampaign;        
    }    
    
}