force-app/main/default/objects/Concept_Note__c/Concept_Note__c.object-meta.xml
<CustomObject>
    <label>Concept Note</label>
    <nameField>
        <label>Concept Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Concept Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Concept_Note__c/fields/Eversign_FO_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Eversign_FO_Document_Id__c</fullName>
    <inlineHelpText>Field Office Eversign Agreement Id</inlineHelpText>
    <label>Eversign FO Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Concept_Note__c/fields/Field_Office_Agreement_Status__c.field-meta.xml
<CustomField>
    <fullName>Field_Office_Agreement_Status__c</fullName>
    <label>Field Office Agreement Signature Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Eversign_Document_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Concept_Note__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <inlineHelpText>Stages of Concept Note Approval, After Submitted Stage till the FA Signed this is controlled by aprroval process</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved-DC</fullName>
            </value>
            <value>
                <fullName>Approved-HoP</fullName>
            </value>
            <value>
                <fullName>Approved - Finance</fullName>
            </value>
            <value>
                <fullName>Approved-Donor</fullName>
            </value>
            <value>
                <fullName>FA-signed</fullName>
            </value>
            <value>
                <fullName>Project Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fund_Allocation__c/Fund_Allocation__c.object-meta.xml
<CustomObject>
    <label>Fund Allocation</label>
    <nameField>
        <displayFormat>FAL-{00000}</displayFormat>
        <label>Fund Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund Allocation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund_Allocation__c/fields/Concept_Note__c.field-meta.xml
<CustomField>
    <fullName>Concept_Note__c</fullName>
    <label>Concept Note</label>
    <referenceTo>Concept_Note__c</referenceTo>
    <relationshipName>Funds_Allocation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fund_Allocation__c/fields/Eversign_Partner_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Eversign_Partner_Document_Id__c</fullName>
    <label>Eversign Partner Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fund_Allocation__c/fields/Partner_Agreement_Signature_Status__c.field-meta.xml
<CustomField>
    <fullName>Partner_Agreement_Signature_Status__c</fullName>
    <label>Partner Agreement Signature Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Eversign_Document_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Eversign_Document_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Deleted</fullName>
    </customValue>
    <customValue>
        <fullName>Archived</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Eversign Document Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SendFundAgreementController.cls
public class SendFundAgreementController {
    
    @AuraEnabled
    public static String sendAgreements(String conceptNoteId) {
        
        Concept_Note__c objConceptNote = EversignConnection.createAgreementFODocument(Label.Field_Office_Funding_Agreement_Template,conceptNoteId);
        List<Fund_Allocation__c> lstFundAllo = EversignConnection.createAgreementPartnerDocument(Label.Partner_Funding_Agreement_Template,conceptNoteId);
        
        update objConceptNote;
        update lstFundAllo;
        
        return 'Agreements sent Sucessfully';
    }
    
    @AuraEnabled
    public static String getAgreementStatus(String conceptNoteId) {
        
        EversignConnection.getDocuments(conceptNoteId);
        
        return 'Agreement Status Updated Successfully';
    }
    
    @AuraEnabled
    public static String isStatusCheck(String conceptNoteId) {
        
        Concept_Note__c objConceptNote  = [SELECT Id,Eversign_FO_Document_Id__c,Field_Office_Agreement_Status__c FROM Concept_Note__c WHERE Id=:conceptNoteId];
        
        List<Fund_Allocation__c> lstFundAllo = [SELECT Id,Eversign_Partner_Document_Id__c ,Concept_Note__c,Partner_Agreement_Signature_Status__c  FROM Fund_Allocation__c WHERE Concept_Note__c=:conceptNoteId];
        
        Set<Id> setCompleted = new Set<Id>();
        Set<Id> setInProgress = new Set<Id>();
        
        for (Fund_Allocation__c objFundAllocation : lstFundAllo) {
                                                          
            if (objFundAllocation.Partner_Agreement_Signature_Status__c == 'Completed') {
                    
            	setCompleted.add(objFundAllocation.Id);
            } 
            else if (objFundAllocation.Partner_Agreement_Signature_Status__c == 'In Progress') {
                    
                setInProgress.add(objFundAllocation.Id);
            }
            else if (objFundAllocation.Partner_Agreement_Signature_Status__c == 'Cancelled') {
                    
                return 'Cancelled';
            } 
        }
        
        if (setCompleted.size() == lstFundAllo.size() && objConceptNote.Field_Office_Agreement_Status__c == 'Completed') {
            
            objConceptNote.Stage__c = 'FA-signed';
            update objConceptNote;
            
            return 'Completed';
            
        }
        else if (objConceptNote.Field_Office_Agreement_Status__c == 'Cancelled') {
            
            return 'Cancelled';
        }
        else if (setInProgress.size() > 0 || objConceptNote.Field_Office_Agreement_Status__c == 'In Progress') {
            
            return 'In Progress';
        }
        
        return 'Draft';
    }

}