force-app/main/default/objects/Beneficiaries__c/Beneficiaries__c.object-meta.xml
<CustomObject>
    <label>Beneficiaries</label>
    <nameField>
        <displayFormat>BENE-{0000}</displayFormat>
        <label>Beneficiaries Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Beneficiaries__c/fields/Concept_Note__c.field-meta.xml
<CustomField>
    <fullName>Concept_Note__c</fullName>
    <label>Concept Note</label>
    <referenceTo>Concept_Note__c</referenceTo>
    <relationshipLabel>Beneficiaries</relationshipLabel>
    <relationshipName>Beneficiaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Beneficiaries__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Beneficiaries</relationshipLabel>
    <relationshipName>Beneficiaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Concept_Note__c/Concept_Note__c.object-meta.xml
<CustomObject>
    <label>Concept Note</label>
    <nameField>
        <label>Concept Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Concept Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donor_Payment_Schedule__c/Donor_Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Donor Payment Schedule</label>
    <nameField>
        <displayFormat>DPS-{00000}</displayFormat>
        <label>Donor Payment Schedule  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donor Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Donor_Payment_Schedule__c/fields/Concept_Note__c.field-meta.xml
<CustomField>
    <fullName>Concept_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Concept Note</label>
    <referenceTo>Concept_Note__c</referenceTo>
    <relationshipLabel>Donor Payment Schedules</relationshipLabel>
    <relationshipName>Donor_Payment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donor_Payment_Schedule__c/fields/Fund_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Fund_Allocation__c</fullName>
    <label>Fund Allocation</label>
    <referenceTo>Fund_Allocation__c</referenceTo>
    <relationshipLabel>Donor Payment Schedules</relationshipLabel>
    <relationshipName>Donor_Payment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Donor_Payment_Schedule__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Donor Payment Schedules</relationshipLabel>
    <relationshipName>Donor_Payment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fund_Allocation__c/Fund_Allocation__c.object-meta.xml
<CustomObject>
    <label>Fund Allocation</label>
    <nameField>
        <displayFormat>FAL-{00000}</displayFormat>
        <label>Fund Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund Allocation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund_Allocation__c/fields/Concept_Note__c.field-meta.xml
<CustomField>
    <fullName>Concept_Note__c</fullName>
    <label>Concept Note</label>
    <referenceTo>Concept_Note__c</referenceTo>
    <relationshipName>Funds_Allocation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fund_Allocation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Funds_Allocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fund_Transfer_Schedule__c/Fund_Transfer_Schedule__c.object-meta.xml
<CustomObject>
    <label>Fund Transfer Schedule</label>
    <nameField>
        <displayFormat>FTS-{00000}</displayFormat>
        <label>Funds Transfer Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund Transfer Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund_Transfer_Schedule__c/fields/Concept_Note__c.field-meta.xml
<CustomField>
    <fullName>Concept_Note__c</fullName>
    <label>Concept Note</label>
    <referenceTo>Concept_Note__c</referenceTo>
    <relationshipName>Funds_Transfer_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fund_Transfer_Schedule__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Funds_Transfer_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Track Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Concept_Note__c.field-meta.xml
<CustomField>
    <fullName>Concept_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Concept Note</label>
    <referenceTo>Concept_Note__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Report_Schedule__c/Report_Schedule__c.object-meta.xml
<CustomObject>
    <label>Report Schedule</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Report Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Report_Schedule__c/fields/Concept_Note__c.field-meta.xml
<CustomField>
    <fullName>Concept_Note__c</fullName>
    <label>Concept Note</label>
    <referenceTo>Concept_Note__c</referenceTo>
    <relationshipLabel>Report Schedules</relationshipLabel>
    <relationshipName>Report_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Report_Schedule__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Report Schedules</relationshipLabel>
    <relationshipName>Report_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HA_ProjectConversionUpdate_TDM.cls
/**
 * @description       : update Related records
 * @author            : Kalpesh.Thakur@HumanAppeal.co.uk
 * @group             : 
 * @last modified on  : 02-08-2022
 * @last modified by  : Kalpesh.Thakur@HumanAppeal.co.uk
 * Modifications Log 
 * Ver   Date         Author                             Modification 
 * 1.0   07-22-2021   Kalpesh.Thakur@HumanAppeal.co.uk   Initial Version
**/
global class HA_ProjectConversionUpdate_TDM extends npsp.TDTM_Runnable {
    
    global override npsp.TDTM_Runnable.DmlWrapper run(List<SObject> newlist,
                                             List<SObject> oldlist,
                                             npsp.TDTM_Runnable.Action triggerAction,
                                             Schema.DescribeSObjectResult objResult) {

        npsp.TDTM_Runnable.dmlWrapper dmlWrapper = new npsp.TDTM_Runnable.DmlWrapper();
        List<Project__c> oldProjectList = (List<Project__c>)oldlist;
        List<Project__c> newProjectList = (List<Project__c>)newlist;
		List<Fund_Allocation__c> updateFundAllocations = new List<Fund_Allocation__c>();
        List<Beneficiaries__c> updateBeneficiaries = new List<Beneficiaries__c>();
        List<Report_Schedule__c> updateReportSchedules = new List<Report_Schedule__c>();
        List<Fund_Transfer_Schedule__c> updateFundTransfers = new List<Fund_Transfer_Schedule__c>();
        List<Donor_Payment_Schedule__c> updateDonorPayments = new List<Donor_Payment_Schedule__c>();
                                                
        if (triggerAction == npsp.TDTM_Runnable.Action.AfterInsert) {

            Map<Id,Project__c> mapNewProject = new Map<Id,Project__c>(newProjectList);
            Map<Id,Id> mapProjectIdConceptNoteId = new Map<Id,Id>();

            for (Project__c objPro : newProjectList) {

                mapProjectIdConceptNoteId.put(objPro.Concept_Note__c,objPro.Id);
            }

            System.debug('****mapProjectIdConceptNoteId'+mapProjectIdConceptNoteId);

            for (Fund_Allocation__c objFundAll : [SELECT Id,Project__c,Concept_Note__c FROM Fund_Allocation__c WHERE Concept_Note__c=:mapProjectIdConceptNoteId.keySet()]) {

                if (mapProjectIdConceptNoteId.containsKey(objFundAll.Concept_Note__c)) {

                    objFundAll.Project__c = mapProjectIdConceptNoteId.get(objFundAll.Concept_Note__c);
                    System.debug('**objFundAll**:--'+objFundAll);
                    updateFundAllocations.add(objFundAll);
                }
            }

            

            for (Beneficiaries__c objBene : [SELECT Id,Project__c,Concept_Note__c FROM Beneficiaries__c WHERE Concept_Note__c=:mapProjectIdConceptNoteId.keySet()]) {

                if (mapProjectIdConceptNoteId.containsKey(objBene.Concept_Note__c)) {

                    objBene.Project__c = mapProjectIdConceptNoteId.get(objBene.Concept_Note__c);
                    System.debug('**objBene**:--'+objBene);
                    updateBeneficiaries.add(objBene);
                }
            }

            

            for (Report_Schedule__c objReportSch : [SELECT Id,Project__c,Concept_Note__c FROM Report_Schedule__c WHERE Concept_Note__c=:mapProjectIdConceptNoteId.keySet()]) {

                if (mapProjectIdConceptNoteId.containsKey(objReportSch.Concept_Note__c)) {

                    objReportSch.Project__c = mapProjectIdConceptNoteId.get(objReportSch.Concept_Note__c);
                    System.debug('**objReportSch**:--'+objReportSch);
                    updateReportSchedules.add(objReportSch);
                }
            }

            

            for (Fund_Transfer_Schedule__c objFundTransfer : [SELECT Id,Project__c,Concept_Note__c FROM Fund_Transfer_Schedule__c WHERE Concept_Note__c=:mapProjectIdConceptNoteId.keySet()]) {

                if (mapProjectIdConceptNoteId.containsKey(objFundTransfer.Concept_Note__c)) {

                    objFundTransfer.Project__c = mapProjectIdConceptNoteId.get(objFundTransfer.Concept_Note__c);
                    System.debug('*objFundTransfer*:--'+objFundTransfer);
                    updateFundTransfers.add(objFundTransfer);
                }
            }

            

            for (Donor_Payment_Schedule__c objDonorPayment : [SELECT Id,Project__c,Concept_Note__c FROM Donor_Payment_Schedule__c WHERE Concept_Note__c=:mapProjectIdConceptNoteId.keySet()]) {

                if (mapProjectIdConceptNoteId.containsKey(objDonorPayment.Concept_Note__c)) {

                    objDonorPayment.Project__c = mapProjectIdConceptNoteId.get(objDonorPayment.Concept_Note__c);
                    System.debug('**objDonorPayment**:--'+objDonorPayment);
                    updateDonorPayments.add(objDonorPayment);
                }
            }


        }
                                                 
        if (!updateFundAllocations.isEmpty()) {
           
             dmlWrapper.objectsToUpdate.addAll(updateFundAllocations);
        }     
        
        if (!updateBeneficiaries.isEmpty()) {
           
            dmlWrapper.objectsToUpdate.addAll(updateBeneficiaries);
       }  
       
       if (!updateReportSchedules.isEmpty()) { 
           
            dmlWrapper.objectsToUpdate.addAll(updateReportSchedules);
        } 

        if (!updateFundTransfers.isEmpty()) {
                
            dmlWrapper.objectsToUpdate.addAll(updateFundTransfers);
        } 

        if (!updateDonorPayments.isEmpty()) {
                
            dmlWrapper.objectsToUpdate.addAll(updateDonorPayments);
        } 
        
        System.debug('****dmlwrapper**:-'+dmlWrapper.objectsToUpdate);                                        
      
      return dmlWrapper;
    }

}