force-app/main/default/objects/Beneficiaries__c/Beneficiaries__c.object-meta.xml
<CustomObject>
    <label>Beneficiaries</label>
    <nameField>
        <displayFormat>BENE-{0000}</displayFormat>
        <label>Beneficiaries Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Beneficiaries__c/fields/Concept_Note__c.field-meta.xml
<CustomField>
    <fullName>Concept_Note__c</fullName>
    <label>Concept Note</label>
    <referenceTo>Concept_Note__c</referenceTo>
    <relationshipLabel>Beneficiaries</relationshipLabel>
    <relationshipName>Beneficiaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Beneficiaries__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Beneficiaries</relationshipLabel>
    <relationshipName>Beneficiaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Concept_Note__c/Concept_Note__c.object-meta.xml
<CustomObject>
    <label>Concept Note</label>
    <nameField>
        <label>Concept Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Concept Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Concept_Note__c/fields/Eversign_FO_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Eversign_FO_Document_Id__c</fullName>
    <inlineHelpText>Field Office Eversign Agreement Id</inlineHelpText>
    <label>Eversign FO Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Concept_Note__c/fields/Field_Office_Agreement_Status__c.field-meta.xml
<CustomField>
    <fullName>Field_Office_Agreement_Status__c</fullName>
    <label>Field Office Agreement Signature Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Eversign_Document_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Concept_Note__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <inlineHelpText>Stages of Concept Note Approval, After Submitted Stage till the FA Signed this is controlled by aprroval process</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved-DC</fullName>
            </value>
            <value>
                <fullName>Approved-HoP</fullName>
            </value>
            <value>
                <fullName>Approved - Finance</fullName>
            </value>
            <value>
                <fullName>Approved-Donor</fullName>
            </value>
            <value>
                <fullName>FA-signed</fullName>
            </value>
            <value>
                <fullName>Project Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donor_Payment_Schedule__c/Donor_Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Donor Payment Schedule</label>
    <nameField>
        <displayFormat>DPS-{00000}</displayFormat>
        <label>Donor Payment Schedule  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donor Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Donor_Payment_Schedule__c/fields/Concept_Note__c.field-meta.xml
<CustomField>
    <fullName>Concept_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Concept Note</label>
    <referenceTo>Concept_Note__c</referenceTo>
    <relationshipLabel>Donor Payment Schedules</relationshipLabel>
    <relationshipName>Donor_Payment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donor_Payment_Schedule__c/fields/Fund_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Fund_Allocation__c</fullName>
    <label>Fund Allocation</label>
    <referenceTo>Fund_Allocation__c</referenceTo>
    <relationshipLabel>Donor Payment Schedules</relationshipLabel>
    <relationshipName>Donor_Payment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Donor_Payment_Schedule__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Donor Payment Schedules</relationshipLabel>
    <relationshipName>Donor_Payment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fund_Allocation__c/Fund_Allocation__c.object-meta.xml
<CustomObject>
    <label>Fund Allocation</label>
    <nameField>
        <displayFormat>FAL-{00000}</displayFormat>
        <label>Fund Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund Allocation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund_Allocation__c/fields/Concept_Note__c.field-meta.xml
<CustomField>
    <fullName>Concept_Note__c</fullName>
    <label>Concept Note</label>
    <referenceTo>Concept_Note__c</referenceTo>
    <relationshipName>Funds_Allocation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fund_Allocation__c/fields/Eversign_Partner_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Eversign_Partner_Document_Id__c</fullName>
    <label>Eversign Partner Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fund_Allocation__c/fields/Partner_Agreement_Signature_Status__c.field-meta.xml
<CustomField>
    <fullName>Partner_Agreement_Signature_Status__c</fullName>
    <label>Partner Agreement Signature Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Eversign_Document_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fund_Allocation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Funds_Allocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fund_Transfer_Schedule__c/Fund_Transfer_Schedule__c.object-meta.xml
<CustomObject>
    <label>Fund Transfer Schedule</label>
    <nameField>
        <displayFormat>FTS-{00000}</displayFormat>
        <label>Funds Transfer Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund Transfer Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund_Transfer_Schedule__c/fields/Concept_Note__c.field-meta.xml
<CustomField>
    <fullName>Concept_Note__c</fullName>
    <label>Concept Note</label>
    <referenceTo>Concept_Note__c</referenceTo>
    <relationshipName>Funds_Transfer_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fund_Transfer_Schedule__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Funds_Transfer_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Track Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Concept_Note__c.field-meta.xml
<CustomField>
    <fullName>Concept_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Concept Note</label>
    <referenceTo>Concept_Note__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Project stage (i-e Concept note, Approved, Marketing etc)</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Extended</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Report_Schedule__c/Report_Schedule__c.object-meta.xml
<CustomObject>
    <label>Report Schedule</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Report Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Report_Schedule__c/fields/Concept_Note__c.field-meta.xml
<CustomField>
    <fullName>Concept_Note__c</fullName>
    <label>Concept Note</label>
    <referenceTo>Concept_Note__c</referenceTo>
    <relationshipLabel>Report Schedules</relationshipLabel>
    <relationshipName>Report_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Report_Schedule__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Report Schedules</relationshipLabel>
    <relationshipName>Report_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Eversign_Document_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Deleted</fullName>
    </customValue>
    <customValue>
        <fullName>Archived</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Eversign Document Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ConceptNoteClone.cls
public class ConceptNoteClone {
    
	@AuraEnabled
    public static String  cloneConceptNote(String conceptNoteId) {
        

        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        List<String> conceptNotefields = new List<String>(schemaMap.get('Concept_Note__c').getDescribe().fields.getMap().keySet());
        List<String> beneficiariesfields = new List<String>(schemaMap.get('Beneficiaries__c').getDescribe().fields.getMap().keySet());
        List<String> fundAllocationfields = new List<String>(schemaMap.get('Fund_Allocation__c').getDescribe().fields.getMap().keySet());
        List<String> donorPaymentSchedulefields = new List<String>(schemaMap.get('Donor_Payment_Schedule__c').getDescribe().fields.getMap().keySet());
        List<String> fundTransferSchedulefields = new List<String>(schemaMap.get('Fund_Transfer_Schedule__c').getDescribe().fields.getMap().keySet());
        List<String> reportSchedulefields = new List<String>(schemaMap.get('Report_Schedule__c').getDescribe().fields.getMap().keySet());
        
		String conceptNQuery = 'SELECT '+String.join(conceptNotefields, ',')+' FROM Concept_Note__c WHERE Id=\''+conceptNoteId+'\'';
        String beneficiariesQuery = 'SELECT '+String.join(beneficiariesfields, ',')+' FROM Beneficiaries__c WHERE Concept_Note__c=\''+conceptNoteId+'\'';
        String fundAlloQuery = 'SELECT '+String.join(fundAllocationfields, ',')+' FROM Fund_Allocation__c WHERE Concept_Note__c=\''+conceptNoteId+'\'';
        String donorPayQuery = 'SELECT '+String.join(donorPaymentSchedulefields, ',')+' FROM Donor_Payment_Schedule__c WHERE Concept_Note__c=\''+conceptNoteId+'\'';
        String fundTransQuery = 'SELECT '+String.join(fundTransferSchedulefields, ',')+' FROM Fund_Transfer_Schedule__c WHERE Concept_Note__c=\''+conceptNoteId+'\'';
        String reportSchQuery = 'SELECT '+String.join(reportSchedulefields, ',')+' FROM Report_Schedule__c WHERE Concept_Note__c=\''+conceptNoteId+'\'';
        
        Savepoint sp;
        Concept_Note__c cnCloneCopy;
        try {
        	
            sp = Database.setSavepoint();
            
            Concept_Note__c objConceptNote = Database.query(conceptNQuery);
            
            cnCloneCopy  = objConceptNote.clone(false, true, false, false);
            cnCloneCopy.Stage__c = 'Draft';
            cnCloneCopy.Eversign_FO_Document_Id__c ='';
            cnCloneCopy.Field_Office_Agreement_Status__c = '';
            insert cnCloneCopy;
            
            List<Fund_Allocation__c> newFundAllocations = new List<Fund_Allocation__c>();
            
            Map<Id,Integer> mapFundAllSeq = new Map<Id,Integer>();
            
            Map<Id,Fund_Allocation__c> mapFundAll = new Map<Id,Fund_Allocation__c>((List<Fund_Allocation__c>)Database.query(fundAlloQuery));
            
            integer i = 0;
            for (Fund_Allocation__c objfundAll : mapFundAll.values()) {
                
                mapFundAllSeq.put(objfundAll.Id,i);
                
                Fund_Allocation__c fundAllCloneCopy  = objfundAll.clone(false, true, false, false);
                fundAllCloneCopy.Concept_Note__c = cnCloneCopy.Id;
                fundAllCloneCopy.Project__c =null;
                fundAllCloneCopy.Eversign_Partner_Document_Id__c = '';
                fundAllCloneCopy.Partner_Agreement_Signature_Status__c  = '';
                newFundAllocations.add(fundAllCloneCopy);
                i++;
            }
            
            if (!newFundAllocations.isEmpty()) {
                
                insert newFundAllocations;
                
                List<Donor_Payment_Schedule__c> newDonorPayments = new List<Donor_Payment_Schedule__c>();
            
                for (Donor_Payment_Schedule__c objDonorPay : Database.query(donorPayQuery)) {
                
                    Donor_Payment_Schedule__c donorPayCloneCopy  = objDonorPay.clone(false, true, false, false);
                    donorPayCloneCopy.Concept_Note__c = cnCloneCopy.Id;
                    donorPayCloneCopy.Project__c =null;
                    donorPayCloneCopy.Fund_Allocation__c = newFundAllocations.get(mapFundAllSeq.get(objDonorPay.Fund_Allocation__c)).Id;
                    newDonorPayments.add(donorPayCloneCopy); 
                } 
                
                 if (!newDonorPayments.isEmpty()) {
                    
                     insert newDonorPayments;
                 } 
            }
            
           
            
            List<Beneficiaries__c> newBeneficiaries = new List<Beneficiaries__c>();
            
            for (Beneficiaries__c objBene : Database.query(beneficiariesQuery)) {
                
                Beneficiaries__c beneCloneCopy  = objBene.clone(false, true, false, false);
                beneCloneCopy.Concept_Note__c = cnCloneCopy.Id;
                beneCloneCopy.Project__c =null;
                newBeneficiaries.add(beneCloneCopy); 
            }
            
            if (!newBeneficiaries.isEmpty()) {
                    
                insert newBeneficiaries;
            } 
            
            
            List<Fund_Transfer_Schedule__c> newFundTransfers = new List<Fund_Transfer_Schedule__c>();
            
            for (Fund_Transfer_Schedule__c objFundTrans : Database.query(fundTransQuery)) {
                
                Fund_Transfer_Schedule__c fundTransCloneCopy  = objFundTrans.clone(false, true, false, false);
                fundTransCloneCopy.Concept_Note__c = cnCloneCopy.Id;
                fundTransCloneCopy.Project__c =null;
                newFundTransfers.add(fundTransCloneCopy); 
            }
            
            if (!newFundTransfers.isEmpty()) {
                    
                insert newFundTransfers;
            } 
            
            List<Report_Schedule__c> newReportSchedules = new List<Report_Schedule__c>();
            
            for (Report_Schedule__c objReportSch : Database.query(reportSchQuery)) {
                
                Report_Schedule__c reportSchCloneCopy  = objReportSch.clone(false, true, false, false);
                reportSchCloneCopy.Concept_Note__c = cnCloneCopy.Id;
                reportSchCloneCopy.Project__c =null;
                newReportSchedules.add(reportSchCloneCopy); 
            }
            
            if (!newReportSchedules.isEmpty()) {
                    
                insert newReportSchedules;
            } 
        }
        catch(Exception exe) {
        	
            Database.rollback(sp);
        }

        return cnCloneCopy.Id;
    }
}